// Auto-generated charm inventory

const specialCharms = [
  // 8ball charms
  { src: 'special/8ball/38.png', category: '8ball', quantity: 1 },
  { src: 'special/8ball/38-gold.png', category: '8ball', quantity: 1 },
  { src: 'special/8ball/39.png', category: '8ball', quantity: 0 },
  { src: 'special/8ball/39-gold.png', category: '8ball', quantity: 0 },
  { src: 'special/8ball/40.png', category: '8ball', quantity: 2 },
  { src: 'special/8ball/40-gold.png', category: '8ball', quantity: 2 },
  { src: 'special/8ball/41.png', category: '8ball', quantity: 2 },
  { src: 'special/8ball/41-gold.png', category: '8ball', quantity: 2 },
  { src: 'special/8ball/42.png', category: '8ball', quantity: 0 },
  { src: 'special/8ball/42-gold.png', category: '8ball', quantity: 0 },
  { src: 'special/8ball/43.png', category: '8ball', quantity: 1 },
  { src: 'special/8ball/43-gold.png', category: '8ball', quantity: 1 },
  { src: 'special/8ball/44.png', category: '8ball', quantity: 2 },
  { src: 'special/8ball/44-gold.png', category: '8ball', quantity: 2 },
  { src: 'special/8ball/45.png', category: '8ball', quantity: 1 },
  { src: 'special/8ball/45-gold.png', category: '8ball', quantity: 1 },
  { src: 'special/8ball/46.png', category: '8ball', quantity: 1 },
  { src: 'special/8ball/46-gold.png', category: '8ball', quantity: 1 },
  { src: 'special/8ball/47-gold.png', category: '8ball', quantity: 1 },
  { src: 'special/8ball/48.png', category: '8ball', quantity: 1 },
  { src: 'special/8ball/48-gold.png', category: '8ball', quantity: 1 },
  { src: 'special/8ball/49.png', category: '8ball', quantity: 1 },
  { src: 'special/8ball/49-gold.png', category: '8ball', quantity: 1 },
  { src: 'special/8ball/50.png', category: '8ball', quantity: 1 },
  // beach charms
  { src: 'special/beach/beach.png', category: 'beach', quantity: 4 },
  { src: 'special/beach/beach1.png', category: 'beach', quantity: 1 },
  { src: 'special/beach/beach2.png', category: 'beach', quantity: 1 },
  { src: 'special/beach/beach3.png', category: 'beach', quantity: 0 },
  { src: 'special/beach/beach4.png', category: 'beach', quantity: 2 },
  { src: 'special/beach/beach5.png', category: 'beach', quantity: 0 },
  { src: 'special/beach/beach6.png', category: 'beach', quantity: 1 },
  { src: 'special/beach/beach7.png', category: 'beach', quantity: 2 },
  { src: 'special/beach/beach8.png', category: 'beach', quantity: 0 },
  { src: 'special/beach/beach9.png', category: 'beach', quantity: 3 },
  { src: 'special/beach/beach10.png', category: 'beach', quantity: 2 },
  { src: 'special/beach/beach11.png', category: 'beach', quantity: 1 },
  { src: 'special/beach/beach12.png', category: 'beach', quantity: 1 },
  { src: 'special/beach/beach13.png', category: 'beach', quantity: 1 },
  { src: 'special/beach/beach14.png', category: 'beach', quantity: 3 },
  { src: 'special/beach/beach15.png', category: 'beach', quantity: 1 },
  { src: 'special/beach/beach16.png', category: 'beach', quantity: 0 },
  { src: 'special/beach/beach17.png', category: 'beach', quantity: 1 },
  { src: 'special/beach/beach18.png', category: 'beach', quantity: 1 },
  { src: 'special/beach/103-gold.png', category: 'beach', quantity: 1 },
  { src: 'special/beach/104-gold.png', category: 'beach', quantity: 1 },
  { src: 'special/beach/105-gold.png', category: 'beach', quantity: 3 },
  { src: 'special/beach/106-gold.png', category: 'beach', quantity: 1 },
  { src: 'special/beach/107-gold.png', category: 'beach', quantity: 3 },
  { src: 'special/beach/108-gold.png', category: 'beach', quantity: 1 },
  { src: 'special/beach/109-gold.png', category: 'beach', quantity: 0 },
  { src: 'special/beach/110-gold.png', category: 'beach', quantity: 0 },
  { src: 'special/beach/111-gold.png', category: 'beach', quantity: 1 },
  { src: 'special/beach/112-gold.png', category: 'beach', quantity: 1 },
  { src: 'special/beach/113-gold.png', category: 'beach', quantity: 1 },
  { src: 'special/beach/114-gold.png', category: 'beach', quantity: 2 },
  { src: 'special/beach/115-gold.png', category: 'beach', quantity: 4 },
  { src: 'special/beach/91-gold.png', category: 'beach', quantity: 0 },
  // bows charms
  { src: 'special/bows/beige.png', category: 'bows', quantity: 19 },
  { src: 'special/bows/62-gold.png', category: 'bows', quantity: 9 },
  { src: 'special/bows/63-gold.png', category: 'bows', quantity: 6 },
  { src: 'special/bows/64-gold.png', category: 'bows', quantity: 20 },
  { src: 'special/bows/65-gold.png', category: 'bows', quantity: 19 },
  { src: 'special/bows/66-gold.png', category: 'bows', quantity: 10 },
  { src: 'special/bows/67-gold.png', category: 'bows', quantity: 16 },
  { src: 'special/bows/68-gold.png', category: 'bows', quantity: 8 },
  { src: 'special/bows/69-gold.png', category: 'bows', quantity: 14 },
  { src: 'special/bows/black.png', category: 'bows', quantity: 20 },
  { src: 'special/bows/dark pink.png', category: 'bows', quantity: 14 },
  { src: 'special/bows/navy.png', category: 'bows', quantity: 10 },
  { src: 'special/bows/pink.png', category: 'bows', quantity: 6 },
  { src: 'special/bows/purple.png', category: 'bows', quantity: 8 },
  { src: 'special/bows/red.png', category: 'bows', quantity: 16 },
  { src: 'special/bows/wwhite.png', category: 'bows', quantity: 9 },
  // simple charms
  { src: 'special/cute and simple/2.png', category: 'simple', quantity: 1 },
  { src: 'special/cute and simple/3.png', category: 'simple', quantity: 1 },
  { src: 'special/cute and simple/4.png', category: 'simple', quantity: 1 },
  { src: 'special/cute and simple/5.png', category: 'simple', quantity: 1 },
  { src: 'special/cute and simple/6.png', category: 'simple', quantity: 1 },
  { src: 'special/cute and simple/7.png', category: 'simple', quantity: 3 },
  { src: 'special/cute and simple/8.png', category: 'simple', quantity: 3 },
  { src: 'special/cute and simple/9.png', category: 'simple', quantity: 2 },
  { src: 'special/cute and simple/10.png', category: 'simple', quantity: 3 },
  { src: 'special/cute and simple/11.png', category: 'simple', quantity: 2 },
  { src: 'special/cute and simple/12.png', category: 'simple', quantity: 5 },
  { src: 'special/cute and simple/13.png', category: 'simple', quantity: 1 },
  { src: 'special/cute and simple/14.png', category: 'simple', quantity: 1 },
  { src: 'special/cute and simple/15.png', category: 'simple', quantity: 1 },
  { src: 'special/cute and simple/16.png', category: 'simple', quantity: 1 },
  { src: 'special/cute and simple/17.png', category: 'simple', quantity: 1 },
  { src: 'special/cute and simple/18.png', category: 'simple', quantity: 2 },
  { src: 'special/cute and simple/20.png', category: 'simple', quantity: 2 },
  { src: 'special/cute and simple/21.png', category: 'simple', quantity: 2 },
  { src: 'special/cute and simple/22.png', category: 'simple', quantity: 2 },
  { src: 'special/cute and simple/23.png', category: 'simple', quantity: 1 },
  { src: 'special/cute and simple/24.png', category: 'simple', quantity: 1 },
  { src: 'special/cute and simple/25.png', category: 'simple', quantity: 1 },
  { src: 'special/cute and simple/26.png', category: 'simple', quantity: 2 },
  { src: 'special/cute and simple/27.png', category: 'simple', quantity: 1 },
  { src: 'special/cute and simple/28.png', category: 'simple', quantity: 1 },
  { src: 'special/cute and simple/29.png', category: 'simple', quantity: 0 },
  { src: 'special/cute and simple/30.png', category: 'simple', quantity: 2 },
  { src: 'special/cute and simple/31.png', category: 'simple', quantity: 2 },
  { src: 'special/cute and simple/32.png', category: 'simple', quantity: 3 },
  { src: 'special/cute and simple/33.png', category: 'simple', quantity: 2 },
  { src: 'special/cute and simple/34.png', category: 'simple', quantity: 2 },
  { src: 'special/cute and simple/35.png', category: 'simple', quantity: 2 },
  { src: 'special/cute and simple/36.png', category: 'simple', quantity: 2 },
  { src: 'special/cute and simple/37.png', category: 'simple', quantity: 2 },
  { src: 'special/cute and simple/c2.png', category: 'simple', quantity: 2 },
  { src: 'special/cute and simple/c3.png', category: 'simple', quantity: 3 },
  { src: 'special/cute and simple/c4.png', category: 'simple', quantity: 1 },
  { src: 'special/cute and simple/c5.png', category: 'simple', quantity: 2 },
  { src: 'special/cute and simple/c6.png', category: 'simple', quantity: 2 },
  { src: 'special/cute and simple/turtle.png', category: 'simple', quantity: 2 },
  { src: 'special/cute and simple/c7.png', category: 'simple', quantity: 5 },
  { src: 'special/cute and simple/c8.png', category: 'simple', quantity: 2 },
  // cutespecials charms
  { src: 'special/cute specials/so cute.png', category: 'cutespecials', quantity: 11 },
  { src: 'special/cute specials/102-gold.png', category: 'cutespecials', quantity: 31 },
  { src: 'special/cute specials/116-gold.png', category: 'cutespecials', quantity: 7 },
  { src: 'special/cute specials/117-gold.png', category: 'cutespecials', quantity: 10 },
  { src: 'special/cute specials/118-gold.png', category: 'cutespecials', quantity: 17 },
  { src: 'special/cute specials/119-gold.png', category: 'cutespecials', quantity: 8 },
  { src: 'special/cute specials/120-gold.png', category: 'cutespecials', quantity: 11 },
  { src: 'special/cute specials/121-gold.png', category: 'cutespecials', quantity: 9 },
  { src: 'special/cute specials/122-gold.png', category: 'cutespecials', quantity: 7 },
  { src: 'special/cute specials/123-gold.png', category: 'cutespecials', quantity: 7 },
  { src: 'special/cute specials/124-gold.png', category: 'cutespecials', quantity: 7 },
  { src: 'special/cute specials/125-gold.png', category: 'cutespecials', quantity: 8 },
  { src: 'special/cute specials/126-gold.png', category: 'cutespecials', quantity: 10 },
  { src: 'special/cute specials/127-gold.png', category: 'cutespecials', quantity: 5 },
  { src: 'special/cute specials/128-gold.png', category: 'cutespecials', quantity: 8 },
  { src: 'special/cute specials/special.png', category: 'cutespecials', quantity: 17 },
  { src: 'special/cute specials/special2.png', category: 'cutespecials', quantity: 46 },
  { src: 'special/cute specials/1-gold.png', category: 'cutespecials', quantity: 46 },
  { src: 'special/cute specials/special3.png', category: 'cutespecials', quantity: 8 },
  { src: 'special/cute specials/special4.png', category: 'cutespecials', quantity: 12 },
  { src: 'special/cute specials/special5.png', category: 'cutespecials', quantity: 18 },
  { src: 'special/cute specials/special6.png', category: 'cutespecials', quantity: 13 },
  { src: 'special/cute specials/special7.png', category: 'cutespecials', quantity: 11 },
  { src: 'special/cute specials/special8.png', category: 'cutespecials', quantity: 13 },
  { src: 'special/cute specials/special9.png', category: 'cutespecials', quantity: 10 },
  { src: 'special/cute specials/special10.png', category: 'cutespecials', quantity: 10 },
  { src: 'special/cute specials/special11.png', category: 'cutespecials', quantity: 7 },
  { src: 'special/cute specials/special12.png', category: 'cutespecials', quantity: 30 },
  { src: 'special/cute specials/special13.png', category: 'cutespecials', quantity: 0 },
  { src: 'special/cute specials/special14.png', category: 'cutespecials', quantity: 1 },
  { src: 'special/cute specials/special15.png', category: 'cutespecials', quantity: 4 },
  { src: 'special/cute specials/special16.png', category: 'cutespecials', quantity: 1 },
  { src: 'special/cute specials/3-gold.png', category: 'cutespecials', quantity: 1 },
  { src: 'special/cute specials/2-gold.png', category: 'cutespecials', quantity: 4 },
  { src: 'special/cute specials/special17.png', category: 'cutespecials', quantity: 8 },
  { src: 'special/cute specials/special18.png', category: 'cutespecials', quantity: 0 },
  { src: 'special/cute specials/special19.png', category: 'cutespecials', quantity: 0 },
  { src: 'special/cute specials/special20.png', category: 'cutespecials', quantity: 0 },
  { src: 'special/cute specials/special21.png', category: 'cutespecials', quantity: 1 },
  { src: 'special/cute specials/special girly.png', category: 'cutespecials', quantity: 5 },
  // cute charms
  { src: 'special/cute/cute.png', category: 'cute', quantity: 0 },
  { src: 'special/cute/cute2.png', category: 'cute', quantity: 0 },
  { src: 'special/cute/cute3.png', category: 'cute', quantity: 0 },
  { src: 'special/cute/cute4.png', category: 'cute', quantity: 0 },
  { src: 'special/cute/cute5.png', category: 'cute', quantity: 2 },
  { src: 'special/cute/cute6.png', category: 'cute', quantity: 0 },
  { src: 'special/cute/cute7.png', category: 'cute', quantity: 0 },
  { src: 'special/cute/cute8.png', category: 'cute', quantity: 1 },
  { src: 'special/cute/cute9.png', category: 'cute', quantity: 0 },
  { src: 'special/cute/cute10.png', category: 'cute', quantity: 0 },
  { src: 'special/cute/cute11.png', category: 'cute', quantity: 0 },
  { src: 'special/cute/cute12.png', category: 'cute', quantity: 1 },
  { src: 'special/cute/cute13.png', category: 'cute', quantity: 0 },
  { src: 'special/cute/cute14.png', category: 'cute', quantity: 0 },
  { src: 'special/cute/cute15.png', category: 'cute', quantity: 0 },
  { src: 'special/cute/cute16.png', category: 'cute', quantity: 0 },
  { src: 'special/cute/cute17.png', category: 'cute', quantity: 1 },
  { src: 'special/cute/cute18.png', category: 'cute', quantity: 2 },
  { src: 'special/cute/cute19.png', category: 'cute', quantity: 1 },
  { src: 'special/cute/cute20.png', category: 'cute', quantity: 1 },
  { src: 'special/cute/cute21.png', category: 'cute', quantity: 1 },
  { src: 'special/cute/cute22.png', category: 'cute', quantity: 1 },
  { src: 'special/cute/cute23.png', category: 'cute', quantity: 1 },
  { src: 'special/cute/cute24.png', category: 'cute', quantity: 1 },
  // mushrooms charms
  { src: 'special/mushrooms/mushroom.png', category: 'mushrooms', quantity: 3 },
  { src: 'special/mushrooms/70-gold.png', category: 'mushrooms', quantity: 1 },
  { src: 'special/mushrooms/71-gold.png', category: 'mushrooms', quantity: 5 },
  { src: 'special/mushrooms/72-gold.png', category: 'mushrooms', quantity: 3 },
  { src: 'special/mushrooms/73-gold.png', category: 'mushrooms', quantity: 2 },
  { src: 'special/mushrooms/mushroom1.png', category: 'mushrooms', quantity: 2 },
  { src: 'special/mushrooms/mushroom2.png', category: 'mushrooms', quantity: 5 },
  { src: 'special/mushrooms/mushroom3.png', category: 'mushrooms', quantity: 1 },
  { src: 'special/mushrooms/mushroom4.png', category: 'mushrooms', quantity: 0 },
  // red charms
  { src: 'special/red/red.png', category: 'red', quantity: 1 },
  { src: 'special/red/36-gold.png', category: 'red', quantity: 10 },
  { src: 'special/red/37-gold.png', category: 'red', quantity: 10 },
  { src: 'special/red/89-gold.png', category: 'red', quantity: 1 },
  { src: 'special/red/90-gold.png', category: 'red', quantity: 5 },
  { src: 'special/red/92-gold.png', category: 'red', quantity: 2 },
  { src: 'special/red/93-gold.png', category: 'red', quantity: 1 },
  { src: 'special/red/94-gold.png', category: 'red', quantity: 8 },
  { src: 'special/red/95-gold.png', category: 'red', quantity: 1 },
  { src: 'special/red/96-gold.png', category: 'red', quantity: 1 },
  { src: 'special/red/97-gold.png', category: 'red', quantity: 5 },
  { src: 'special/red/98-gold.png', category: 'red', quantity: 2 },
  { src: 'special/red/99-gold.png', category: 'red', quantity: 2 },
  { src: 'special/red/100-gold.png', category: 'red', quantity: 1 },
  { src: 'special/red/101-gold.png', category: 'red', quantity: 2 },
  { src: 'special/red/red1.png', category: 'red', quantity: 2 },
  { src: 'special/red/red2.png', category: 'red', quantity: 5 },
  { src: 'special/red/red3.png', category: 'red', quantity: 1 },
  { src: 'special/red/red4.png', category: 'red', quantity: 2 },
  { src: 'special/red/red5.png', category: 'red', quantity: 2 },
  { src: 'special/red/red6.png', category: 'red', quantity: 1 },
  { src: 'special/red/red7.png', category: 'red', quantity: 2 },
  { src: 'special/red/red8.png', category: 'red', quantity: 1 },
  { src: 'special/red/red9.png', category: 'red', quantity: 8 },
  { src: 'special/red/red10.png', category: 'red', quantity: 5 },
  { src: 'special/red/red11.png', category: 'red', quantity: 1 },
  { src: 'special/red/red12.png', category: 'red', quantity: 2 },
  // teddy charms
  { src: 'special/teddy/teddy.png', category: 'teddy', quantity: 3 },
  { src: 'special/teddy/84-gold.png', category: 'teddy', quantity: 12 },
  { src: 'special/teddy/85-gold.png', category: 'teddy', quantity: 9 },
  { src: 'special/teddy/86-gold.png', category: 'teddy', quantity: 5 },
  { src: 'special/teddy/87-gold.png', category: 'teddy', quantity: 3 },
  { src: 'special/teddy/88-gold.png', category: 'teddy', quantity: 6 },
  { src: 'special/teddy/teddy2.png', category: 'teddy', quantity: 5 },
  { src: 'special/teddy/teddy3.png', category: 'teddy', quantity: 6 },
  { src: 'special/teddy/teddy4.png', category: 'teddy', quantity: 9 },
  { src: 'special/teddy/128-gold.png', category: 'teddy', quantity: 9 },
  { src: 'special/teddy/teddy5.png', category: 'teddy', quantity: 9 },
  { src: 'special/teddy/teddy6.png', category: 'teddy', quantity: 12 },
];

const rareCharms = [
  // dangly charms
  { src: 'rares/dangly/dangly.png', category: 'dangly', quantity: 8 },
  { src: 'rares/dangly/9-gold.png', category: 'dangly', quantity: 1 },
  { src: 'rares/dangly/10.png', category: 'dangly', quantity: 1 },
  { src: 'rares/dangly/11.png', category: 'dangly', quantity: 1 },
  { src: 'rares/dangly/12-gold.png', category: 'dangly', quantity: 1 },
  { src: 'rares/dangly/13.png', category: 'dangly', quantity: 1 },
  { src: 'rares/dangly/14-gold.png', category: 'dangly', quantity: 1 },
  { src: 'rares/dangly/15-gold.png', category: 'dangly', quantity: 4 },
  { src: 'rares/dangly/16.png', category: 'dangly', quantity: 4 },
  // disney charms
  { src: 'rares/disney/bluemonster.png', category: 'disney', quantity: 2 },
  { src: 'rares/disney/74-gold.png', category: 'disney', quantity: 4 },
  { src: 'rares/disney/75-gold.png', category: 'disney', quantity: 3 },
  { src: 'rares/disney/76-gold.png', category: 'disney', quantity: 5 },
  { src: 'rares/disney/77-gold.png', category: 'disney', quantity: 3 },
  { src: 'rares/disney/78-gold.png', category: 'disney', quantity: 7 },
  { src: 'rares/disney/79-gold.png', category: 'disney', quantity: 6 },
  { src: 'rares/disney/80-gold.png', category: 'disney', quantity: 7 },
  { src: 'rares/disney/81-gold.png', category: 'disney', quantity: 2 },
  { src: 'rares/disney/82-gold.png', category: 'disney', quantity: 2 },
  { src: 'rares/disney/bunny.png', category: 'disney', quantity: 3 },
  { src: 'rares/disney/disneycat pink.png', category: 'disney', quantity: 6 },
  { src: 'rares/disney/disneycat.png', category: 'disney', quantity: 7 },
  { src: 'rares/disney/fox.png', category: 'disney', quantity: 5 },
  { src: 'rares/disney/greenmonster.png', category: 'disney', quantity: 7 },
  { src: 'rares/disney/pinkstitch.png', category: 'disney', quantity: 4 },
  { src: 'rares/disney/snjab.png', category: 'disney', quantity: 2 },
  { src: 'rares/disney/stitch.png', category: 'disney', quantity: 3 },
  // gold charms
  { src: 'rares/gold/gold.png', category: 'gold', quantity: 0 },
  { src: 'rares/gold/gold17.png', category: 'gold', quantity: 1 },
  { src: 'rares/gold/gold2.png', category: 'gold', quantity: 2 },
  { src: 'rares/gold/gold3.png', category: 'gold', quantity: 1 },
  { src: 'rares/gold/gold4.png', category: 'gold', quantity: 0 },
  { src: 'rares/gold/gold5.png', category: 'gold', quantity: 1 },
  { src: 'rares/gold/gold6.png', category: 'gold', quantity: 1 },
  { src: 'rares/gold/gold7.png', category: 'gold', quantity: 0 },
  { src: 'rares/gold/gold8.png', category: 'gold', quantity: 2 },
  { src: 'rares/gold/gold9.png', category: 'gold', quantity: 3 },
  { src: 'rares/gold/gold10.png', category: 'gold', quantity: 0 },
  { src: 'rares/gold/gold11.png', category: 'gold', quantity: 4 },
  { src: 'rares/gold/gold12.png', category: 'gold', quantity: 0 },
  { src: 'rares/gold/gold13.png', category: 'gold', quantity: 0 },
  { src: 'rares/gold/gold14.png', category: 'gold', quantity: 1 },
  { src: 'rares/gold/gold15.png', category: 'gold', quantity: 0 },
  // graduation charms
  { src: 'rares/graduation/grad.png', category: 'graduation', quantity: 1 },
  // hgs charms
  { src: 'rares/hgs/hgs.png', category: 'hgs', quantity: 0 },
  { src: 'rares/hgs/hgs2.png', category: 'hgs', quantity: 0 },
  { src: 'rares/hgs/hgs3.png', category: 'hgs', quantity: 1 },
  { src: 'rares/hgs/hgs4.png', category: 'hgs', quantity: 0 },
  { src: 'rares/hgs/25.png', category: 'hgs', quantity: 1 },
  { src: 'rares/hgs/20.png', category: 'hgs', quantity: 1 },
  { src: 'rares/hgs/27.png', category: 'hgs', quantity: 1 },
  { src: 'rares/hgs/21.png', category: 'hgs', quantity: 1 },
  { src: 'rares/hgs/22.png', category: 'hgs', quantity: 1 },
  { src: 'rares/hgs/23.png', category: 'hgs', quantity: 1 },
  { src: 'rares/hgs/24.png', category: 'hgs', quantity: 1 },
  { src: 'rares/hgs/26.png', category: 'hgs', quantity: 1 },
  { src: 'rares/hgs/hgs5.png', category: 'hgs', quantity: 2 },
  { src: 'rares/hgs/hgs6.png', category: 'hgs', quantity: 0 },
  { src: 'rares/hgs/hgs7.png', category: 'hgs', quantity: 1 },
  { src: 'rares/hgs/129.png', category: 'hgs', quantity: 1 },
  { src: 'rares/hgs/130.png', category: 'hgs', quantity: 1 },
  { src: 'rares/hgs/hgs9.png', category: 'hgs', quantity: 1 },
  { src: 'rares/hgs/hgs10.png', category: 'hgs', quantity: 1 },
  { src: 'rares/hgs/hgs11.png', category: 'hgs', quantity: 0 },
  { src: 'rares/hgs/hgs12.png', category: 'hgs', quantity: 0 },
  { src: 'rares/hgs/hgs13.png', category: 'hgs', quantity: 1 },
  { src: 'rares/hgs/hgs14.png', category: 'hgs', quantity: 0 },
  { src: 'rares/hgs/hgs15.png', category: 'hgs', quantity: 0 },
  { src: 'rares/hgs/hgs16.png', category: 'hgs', quantity: 1 },
  { src: 'rares/hgs/hgs17.png', category: 'hgs', quantity: 0 },
  // long charms
  { src: 'rares/long/long.png', category: 'long', quantity: 0 },
  { src: 'rares/long/long2.png', category: 'long', quantity: 1 },
  // love charms
  { src: 'rares/love/best.png', category: 'love', quantity: 1 },
  { src: 'rares/love/ends.png', category: 'love', quantity: 1 },
  { src: 'rares/love/fri.png', category: 'love', quantity: 1 },
  { src: 'rares/love/6.png', category: 'love', quantity: 1 },
  { src: 'rares/love/7.png', category: 'love', quantity: 1 },
  { src: 'rares/love/19.png', category: 'love', quantity: 1 },
  { src: 'rares/love/love.png', category: 'love', quantity: 1 },
  { src: 'rares/love/love2.png', category: 'love', quantity: 1 },
  { src: 'rares/love/love3.png', category: 'love', quantity: 1 },
  { src: 'rares/love/love4.png', category: 'love', quantity: 0 },
  { src: 'rares/love/love5.png', category: 'love', quantity: 1 },
  { src: 'rares/love/love6.png', category: 'love', quantity: 0 },
  { src: 'rares/love/love7.png', category: 'love', quantity: 0 },
  { src: 'rares/love/love8.png', category: 'love', quantity: 3 },
  { src: 'rares/love/love9.png', category: 'love', quantity: 3 },
  { src: 'rares/love/love10.png', category: 'love', quantity: 1 },
  { src: 'rares/love/love11.png', category: 'love', quantity: 1 },
  { src: 'rares/love/mrmrs1.png', category: 'love', quantity: 1 },
  { src: 'rares/love/mrmrs2.png', category: 'love', quantity: 1 },
  // sanrio charms
  { src: 'rares/sanrio/50-gold.png', category: 'sanrio', quantity: 11 },
  { src: 'rares/sanrio/51.png', category: 'sanrio', quantity: 10 },
  { src: 'rares/sanrio/51-gold.png', category: 'sanrio', quantity: 11 },
  { src: 'rares/sanrio/52.png', category: 'sanrio', quantity: 10 },
  { src: 'rares/sanrio/52-gold.png', category: 'sanrio', quantity: 9 },
  { src: 'rares/sanrio/53.png', category: 'sanrio', quantity: 10 },
  { src: 'rares/sanrio/53-gold.png', category: 'sanrio', quantity: 11 },
  { src: 'rares/sanrio/54.png', category: 'sanrio', quantity: 11 },
  { src: 'rares/sanrio/54-gold.png', category: 'sanrio', quantity: 11 },
  { src: 'rares/sanrio/55.png', category: 'sanrio', quantity: 11 },
  { src: 'rares/sanrio/55-gold.png', category: 'sanrio', quantity: 11 },
  { src: 'rares/sanrio/56.png', category: 'sanrio', quantity: 11 },
  { src: 'rares/sanrio/56-gold.png', category: 'sanrio', quantity: 10 },
  { src: 'rares/sanrio/57.png', category: 'sanrio', quantity: 10 },
  { src: 'rares/sanrio/57-gold.png', category: 'sanrio', quantity: 11 },
  { src: 'rares/sanrio/58.png', category: 'sanrio', quantity: 11 },
  { src: 'rares/sanrio/58-gold.png', category: 'sanrio', quantity: 8 },
  { src: 'rares/sanrio/59.png', category: 'sanrio', quantity: 8 },
  { src: 'rares/sanrio/59-gold.png', category: 'sanrio', quantity: 11 },
  { src: 'rares/sanrio/60.png', category: 'sanrio', quantity: 11 },
  { src: 'rares/sanrio/60-gold.png', category: 'sanrio', quantity: 12 },
  { src: 'rares/sanrio/61.png', category: 'sanrio', quantity: 11 },
  { src: 'rares/sanrio/61-gold.png', category: 'sanrio', quantity: 10 },
  { src: 'rares/sanrio/62.png', category: 'sanrio', quantity: 10 },
  { src: 'rares/sanrio/metalkitty.png', category: 'sanrio', quantity: 9 },
  { src: 'rares/sanrio/83-gold.png', category: 'sanrio', quantity: 9 },
  // sporty charms
  { src: 'rares/sporty/sporty.png', category: 'sporty', quantity: 3 },
  { src: 'rares/sporty/18-gold.png', category: 'sporty', quantity: 1 },
  { src: 'rares/sporty/sporty2.png', category: 'sporty', quantity: 3 },
  { src: 'rares/sporty/sporty3.png', category: 'sporty', quantity: 4 },
  { src: 'rares/sporty/sporty4.png', category: 'sporty', quantity: 3 },
  { src: 'rares/sporty/sporty5.png', category: 'sporty', quantity: 1 },
  { src: 'rares/sporty/sporty6.png', category: 'sporty', quantity: 1 },
  { src: 'rares/sporty/sporty7.png', category: 'sporty', quantity: 3 },
  { src: 'rares/sporty/sporty8.png', category: 'sporty', quantity: 0 },
  { src: 'rares/sporty/30.png', category: 'sporty', quantity: 1 },
  { src: 'rares/sporty/sporty9.png', category: 'sporty', quantity: 1 },
  { src: 'rares/sporty/sporty10.png', category: 'sporty', quantity: 1 },
  { src: 'rares/sporty/sporty11.png', category: 'sporty', quantity: 1 },
  { src: 'rares/sporty/sporty12.png', category: 'sporty', quantity: 0 },
  { src: 'rares/sporty/sporty13.png', category: 'sporty', quantity: 1 },
  { src: 'rares/sporty/sporty14.png', category: 'sporty', quantity: 1 },
  { src: 'rares/sporty/sporty15.png', category: 'sporty', quantity: 1 },
  { src: 'rares/sporty/29.png', category: 'sporty', quantity: 1 },
  { src: 'rares/sporty/31.png', category: 'sporty', quantity: 1 },
];

