// charms.js - Use IIFE to prevent global pollution
(function() {
    // Only declare if not already declared
    if (typeof window.specialCharms === 'undefined') {
         window.specialCharms = [
  // 8ball charms
 
  // beach charms
  { src: 'special/beach/beach.png', category: 'beach', quantity: 3 },
  { src: 'special/beach/beach1.png', category: 'beach', quantity: 1 },
  { src: 'special/beach/beach2.png', category: 'beach', quantity: 1 },
  { src: 'special/beach/beach3.png', category: 'beach', quantity: 0 },
  { src: 'special/beach/beach4.png', category: 'beach', quantity: 2 },
  { src: 'special/beach/beach5.png', category: 'beach', quantity: 0 },
  { src: 'special/beach/beach6.png', category: 'beach', quantity: 1 },
  { src: 'special/beach/beach7.png', category: 'beach', quantity: 2 },
  { src: 'special/beach/beach8.png', category: 'beach', quantity: 0 },
  { src: 'special/beach/beach9.png', category: 'beach', quantity: 3 },
  { src: 'special/beach/beach10.png', category: 'beach', quantity: 2 },
  { src: 'special/beach/beach11.png', category: 'beach', quantity: 1 },
  { src: 'special/beach/beach12.png', category: 'beach', quantity: 1 },
  { src: 'special/beach/beach13.png', category: 'beach', quantity: 1 },
  { src: 'special/beach/beach14.png', category: 'beach', quantity: 3 },
  { src: 'special/beach/beach15.png', category: 'beach', quantity: 1 },
  { src: 'special/beach/beach16.png', category: 'beach', quantity: 0 },
  { src: 'special/beach/beach17.png', category: 'beach', quantity: 1 },
  { src: 'special/beach/beach18.png', category: 'beach', quantity: 0 },
  { src: 'special/beach/103-gold.png', category: 'beach', quantity: 1 },
  { src: 'special/beach/104-gold.png', category: 'beach', quantity: 1 },
  { src: 'special/beach/105-gold.png', category: 'beach', quantity: 3 },
  { src: 'special/beach/106-gold.png', category: 'beach', quantity: 1 },
  { src: 'special/beach/107-gold.png', category: 'beach', quantity: 3 },
  { src: 'special/beach/108-gold.png', category: 'beach', quantity: 1 },
  { src: 'special/beach/109-gold.png', category: 'beach', quantity: 0 },
  { src: 'special/beach/110-gold.png', category: 'beach', quantity: 0 },
  { src: 'special/beach/111-gold.png', category: 'beach', quantity: 1 },
  { src: 'special/beach/112-gold.png', category: 'beach', quantity: 1 },
  { src: 'special/beach/113-gold.png', category: 'beach', quantity: 1 },
  { src: 'special/beach/114-gold.png', category: 'beach', quantity: 2 },
  { src: 'special/beach/115-gold.png', category: 'beach', quantity: 3 },
  { src: 'special/beach/91-gold.png', category: 'beach', quantity: 0 },
  { src: 'special/beach/x1.png', category: 'beach', quantity: 1 },
  { src: 'special/beach/x10-gold.png', category: 'beach', quantity: 1 },
  { src: 'special/beach/x11.png', category: 'beach', quantity: 1 },
  { src: 'special/beach/x12-gold.png', category: 'beach', quantity: 1 },
  { src: 'special/beach/x13.png', category: 'beach', quantity: 1 },
  { src: 'special/beach/x14-gold.png', category: 'beach', quantity: 1 },
  { src: 'special/beach/x15.png', category: 'beach', quantity: 1 },
  { src: 'special/beach/x16-gold.png', category: 'beach', quantity: 1 },
  { src: 'special/beach/x17.png', category: 'beach', quantity: 0 },
  { src: 'special/beach/x18-gold.png', category: 'beach', quantity: 0 },
  { src: 'special/beach/x19.png', category: 'beach', quantity: 1 },
  { src: 'special/beach/x2-gold.png', category: 'beach', quantity: 1 },
  { src: 'special/beach/x20-gold.png', category: 'beach', quantity: 1 },
  { src: 'special/beach/x21.png', category: 'beach', quantity: 1 },
  { src: 'special/beach/x22-gold.png', category: 'beach', quantity: 1 },
  { src: 'special/beach/x3.png', category: 'beach', quantity: 1 },
  { src: 'special/beach/x4-gold.png', category: 'beach', quantity: 1 },
  { src: 'special/beach/x5.png', category: 'beach', quantity: 1 },
  { src: 'special/beach/x6-gold.png', category: 'beach', quantity: 1 },
  { src: 'special/beach/x7.png', category: 'beach', quantity: 1 },
  { src: 'special/beach/x8-gold.png', category: 'beach', quantity: 1 },
  { src: 'special/beach/x9.png', category: 'beach', quantity: 1 },
  // bows charms
  { src: 'special/bows/beige.png', category: 'bows', quantity: 19 },
  { src: 'special/bows/62-gold.png', category: 'bows', quantity: 9 },
  { src: 'special/bows/63-gold.png', category: 'bows', quantity: 0 },
  { src: 'special/bows/64-gold.png', category: 'bows', quantity: 20 },
  { src: 'special/bows/65-gold.png', category: 'bows', quantity: 19 },
  { src: 'special/bows/66-gold.png', category: 'bows', quantity: 10 },
  { src: 'special/bows/67-gold.png', category: 'bows', quantity: 16 },
  { src: 'special/bows/68-gold.png', category: 'bows', quantity: 8 },
  { src: 'special/bows/69-gold.png', category: 'bows', quantity: 14 },
  { src: 'special/bows/black.png', category: 'bows', quantity: 20 },
  { src: 'special/bows/dark pink.png', category: 'bows', quantity: 14 },
  { src: 'special/bows/navy.png', category: 'bows', quantity: 10 },
  { src: 'special/bows/pink.png', category: 'bows', quantity: 0 },
  { src: 'special/bows/purple.png', category: 'bows', quantity: 8 },
  { src: 'special/bows/red.png', category: 'bows', quantity: 16 },
  { src: 'special/bows/wwhite.png', category: 'bows', quantity: 9 },
  // simple charms
  { src: 'special/cute and simple/2.png', category: 'simple', quantity: 1 },
  { src: 'special/cute and simple/3.png', category: 'simple', quantity: 1 },
  { src: 'special/cute and simple/4.png', category: 'simple', quantity: 0 },
  { src: 'special/cute and simple/5.png', category: 'simple', quantity: 0 },
  { src: 'special/cute and simple/6.png', category: 'simple', quantity: 1 },
  { src: 'special/cute and simple/7.png', category: 'simple', quantity: 2 },
  { src: 'special/cute and simple/8.png', category: 'simple', quantity: 2 },
  { src: 'special/cute and simple/9.png', category: 'simple', quantity: 2 },
  { src: 'special/cute and simple/10.png', category: 'simple', quantity: 3 },
  { src: 'special/cute and simple/11.png', category: 'simple', quantity: 2 },
  { src: 'special/cute and simple/12.png', category: 'simple', quantity: 5 },
  { src: 'special/cute and simple/13.png', category: 'simple', quantity: 1 },
  { src: 'special/cute and simple/14.png', category: 'simple', quantity: 0 },
  { src: 'special/cute and simple/15.png', category: 'simple', quantity: 1 },
  { src: 'special/cute and simple/16.png', category: 'simple', quantity: 1 },
  { src: 'special/cute and simple/17.png', category: 'simple', quantity: 1 },
  { src: 'special/cute and simple/18.png', category: 'simple', quantity: 2 },
  { src: 'special/cute and simple/20.png', category: 'simple', quantity: 2 },
  { src: 'special/cute and simple/21.png', category: 'simple', quantity: 2 },
  { src: 'special/cute and simple/22.png', category: 'simple', quantity: 2 },
  { src: 'special/cute and simple/23.png', category: 'simple', quantity: 1 },
  { src: 'special/cute and simple/24.png', category: 'simple', quantity: 1 },
  { src: 'special/cute and simple/25.png', category: 'simple', quantity: 1 },
  { src: 'special/cute and simple/26.png', category: 'simple', quantity: 1 },
  { src: 'special/cute and simple/27.png', category: 'simple', quantity: 0 },
  { src: 'special/cute and simple/28.png', category: 'simple', quantity: 1 },
  { src: 'special/cute and simple/29.png', category: 'simple', quantity: 0 },
  { src: 'special/cute and simple/30.png', category: 'simple', quantity: 2 },
  { src: 'special/cute and simple/31.png', category: 'simple', quantity: 2 },
  { src: 'special/cute and simple/32.png', category: 'simple', quantity: 3 },
  { src: 'special/cute and simple/33.png', category: 'simple', quantity: 2 },
  { src: 'special/cute and simple/34.png', category: 'simple', quantity: 2 },
  { src: 'special/cute and simple/35.png', category: 'simple', quantity: 1 },
  { src: 'special/cute and simple/36.png', category: 'simple', quantity: 2 },
  { src: 'special/cute and simple/37.png', category: 'simple', quantity: 2 },
  { src: 'special/cute and simple/c2.png', category: 'simple', quantity: 1 },
  { src: 'special/cute and simple/c3.png', category: 'simple', quantity: 3 },
  { src: 'special/cute and simple/c4.png', category: 'simple', quantity: 1 },
  { src: 'special/cute and simple/c5.png', category: 'simple', quantity: 1 },
  { src: 'special/cute and simple/c6.png', category: 'simple', quantity: 2 },
  { src: 'special/cute and simple/turtle.png', category: 'simple', quantity: 2 },
  { src: 'special/cute and simple/c7.png', category: 'simple', quantity: 5 },
  { src: 'special/cute and simple/c8.png', category: 'simple', quantity: 2 },
  // cutespecials charms
  { src: 'special/cute specials/so cute.png', category: 'cutespecials', quantity: 11 },
  { src: 'special/cute specials/102-gold.png', category: 'cutespecials', quantity: 31 },
  { src: 'special/cute specials/116-gold.png', category: 'cutespecials', quantity: 6 },
  { src: 'special/cute specials/117-gold.png', category: 'cutespecials', quantity: 7 },
  { src: 'special/cute specials/118-gold.png', category: 'cutespecials', quantity: 15 },
  { src: 'special/cute specials/119-gold.png', category: 'cutespecials', quantity: 8 },
  { src: 'special/cute specials/120-gold.png', category: 'cutespecials', quantity: 11 },
  { src: 'special/cute specials/121-gold.png', category: 'cutespecials', quantity: 9 },
  { src: 'special/cute specials/122-gold.png', category: 'cutespecials', quantity: 7 },
  { src: 'special/cute specials/123-gold.png', category: 'cutespecials', quantity: 7 },
  { src: 'special/cute specials/124-gold.png', category: 'cutespecials', quantity: 7 },
  { src: 'special/cute specials/125-gold.png', category: 'cutespecials', quantity: 8 },
  { src: 'special/cute specials/126-gold.png', category: 'cutespecials', quantity: 10 },
  { src: 'special/cute specials/127-gold.png', category: 'cutespecials', quantity: 5 },
  { src: 'special/cute specials/128-gold.png', category: 'cutespecials', quantity: 7 },
  { src: 'special/cute specials/special.png', category: 'cutespecials', quantity: 15 },
  { src: 'special/cute specials/special2.png', category: 'cutespecials', quantity: 46 },
  { src: 'special/cute specials/1-gold.png', category: 'cutespecials', quantity: 46 },
  { src: 'special/cute specials/special3.png', category: 'cutespecials', quantity: 8 },
  { src: 'special/cute specials/special4.png', category: 'cutespecials', quantity: 12 },
  { src: 'special/cute specials/special5.png', category: 'cutespecials', quantity: 18 },
  { src: 'special/cute specials/special6.png', category: 'cutespecials', quantity: 13 },
  { src: 'special/cute specials/special7.png', category: 'cutespecials', quantity: 11 },
  { src: 'special/cute specials/special8.png', category: 'cutespecials', quantity: 13 },
  { src: 'special/cute specials/special9.png', category: 'cutespecials', quantity: 10 },
  { src: 'special/cute specials/special10.png', category: 'cutespecials', quantity: 7 },
  { src: 'special/cute specials/special11.png', category: 'cutespecials', quantity: 6 },
  { src: 'special/cute specials/special12.png', category: 'cutespecials', quantity: 30 },
  { src: 'special/cute specials/special13.png', category: 'cutespecials', quantity: 0 },
  { src: 'special/cute specials/special14.png', category: 'cutespecials', quantity: 1 },
  { src: 'special/cute specials/special15.png', category: 'cutespecials', quantity: 3 },
  { src: 'special/cute specials/special16.png', category: 'cutespecials', quantity: 1 },
  { src: 'special/cute specials/3-gold.png', category: 'cutespecials', quantity: 1 },
  { src: 'special/cute specials/2-gold.png', category: 'cutespecials', quantity: 3 },
  { src: 'special/cute specials/special17.png', category: 'cutespecials', quantity: 7 },
  { src: 'special/cute specials/special18.png', category: 'cutespecials', quantity: 0 },
  { src: 'special/cute specials/special19.png', category: 'cutespecials', quantity: 0 },
  { src: 'special/cute specials/special20.png', category: 'cutespecials', quantity: 0 },
  { src: 'special/cute specials/special21.png', category: 'cutespecials', quantity: 0 },
  { src: 'special/cute specials/special girly.png', category: 'cutespecials', quantity: 5 },
  // cute charms
  { src: 'special/cute/cute.png', category: 'cute', quantity: 0 },
  { src: 'special/cute/cute2.png', category: 'cute', quantity: 0 },
  { src: 'special/cute/cute3.png', category: 'cute', quantity: 0 },
  { src: 'special/cute/cute4.png', category: 'cute', quantity: 0 },
  { src: 'special/cute/cute5.png', category: 'cute', quantity: 2 },
  { src: 'special/cute/cute6.png', category: 'cute', quantity: 0 },
  { src: 'special/cute/cute7.png', category: 'cute', quantity: 0 },
  { src: 'special/cute/cute8.png', category: 'cute', quantity: 1 },
  { src: 'special/cute/cute9.png', category: 'cute', quantity: 0 },
  { src: 'special/cute/cute10.png', category: 'cute', quantity: 0 },
  { src: 'special/cute/cute11.png', category: 'cute', quantity: 0 },
  { src: 'special/cute/cute12.png', category: 'cute', quantity: 1 },
  { src: 'special/cute/cute13.png', category: 'cute', quantity: 0 },
  { src: 'special/cute/cute14.png', category: 'cute', quantity: 0 },
  { src: 'special/cute/cute15.png', category: 'cute', quantity: 0 },
  { src: 'special/cute/cute16.png', category: 'cute', quantity: 0 },
  { src: 'special/cute/cute17.png', category: 'cute', quantity: 1 },
  { src: 'special/cute/cute18.png', category: 'cute', quantity: 2 },
  { src: 'special/cute/cute19.png', category: 'cute', quantity: 1 },
  { src: 'special/cute/cute20.png', category: 'cute', quantity: 1 },
  { src: 'special/cute/cute21.png', category: 'cute', quantity: 1 },
  { src: 'special/cute/cute22.png', category: 'cute', quantity: 1 },
  { src: 'special/cute/cute23.png', category: 'cute', quantity: 1 },
  { src: 'special/cute/cute24.png', category: 'cute', quantity: 1 },
  // mushrooms charms
  { src: 'special/mushrooms/mushroom.png', category: 'mushrooms', quantity: 3 },
  { src: 'special/mushrooms/70-gold.png', category: 'mushrooms', quantity: 4 },
  { src: 'special/mushrooms/71-gold.png', category: 'mushrooms', quantity: 5 },
  { src: 'special/mushrooms/72-gold.png', category: 'mushrooms', quantity: 3 },
  { src: 'special/mushrooms/73-gold.png', category: 'mushrooms', quantity: 2 },
  { src: 'special/mushrooms/mushroom1.png', category: 'mushrooms', quantity: 2 },
  { src: 'special/mushrooms/mushroom2.png', category: 'mushrooms', quantity: 5 },
  { src: 'special/mushrooms/mushroom3.png', category: 'mushrooms', quantity: 4 },
  { src: 'special/mushrooms/mushroom4.png', category: 'mushrooms', quantity: 3 },
  { src: 'special/mushrooms/84-gold.png', category: 'mushrooms', quantity: 1 },
  // red charms
  { src: 'special/red/red.png', category: 'red', quantity: 0 },
  { src: 'special/red/36-gold.png', category: 'red', quantity: 0 },
  { src: 'special/red/37-gold.png', category: 'red', quantity: 0 },
  { src: 'special/red/89-gold.png', category: 'red', quantity: 1 },
  { src: 'special/red/90-gold.png', category: 'red', quantity: 5 },
  { src: 'special/red/92-gold.png', category: 'red', quantity: 2 },
  { src: 'special/red/93-gold.png', category: 'red', quantity: 1 },
  { src: 'special/red/94-gold.png', category: 'red', quantity: 4 },
  { src: 'special/red/95-gold.png', category: 'red', quantity: 0 },
  { src: 'special/red/96-gold.png', category: 'red', quantity: 1 },
  { src: 'special/red/97-gold.png', category: 'red', quantity: 5 },
  { src: 'special/red/98-gold.png', category: 'red', quantity: 2 },
  { src: 'special/red/99-gold.png', category: 'red', quantity: 2 },
  { src: 'special/red/100-gold.png', category: 'red', quantity: 1 },
  { src: 'special/red/101-gold.png', category: 'red', quantity: 2 },
  { src: 'special/red/red1.png', category: 'red', quantity: 2 },
  { src: 'special/red/red2.png', category: 'red', quantity: 5 },
  { src: 'special/red/red3.png', category: 'red', quantity: 1 },
  { src: 'special/red/red4.png', category: 'red', quantity: 2 },
  { src: 'special/red/red5.png', category: 'red', quantity: 2 },
  { src: 'special/red/red6.png', category: 'red', quantity: 1 },
  { src: 'special/red/red7.png', category: 'red', quantity: 2 },
  { src: 'special/red/red8.png', category: 'red', quantity: 1 },
  { src: 'special/red/red9.png', category: 'red', quantity: 4 },
  { src: 'special/red/red10.png', category: 'red', quantity: 5 },
  { src: 'special/red/red11.png', category: 'red', quantity: 1 },
  { src: 'special/red/red12.png', category: 'red', quantity: 2 },
  { src: 'special/new-collection/1.png', category: 'red', quantity: 1 },
  { src: 'special/new-collection/4.png', category: 'red', quantity: 1 },
  { src: 'special/new-collection/6.png', category: 'red', quantity: 1 },
  { src: 'special/new-collection/8.png', category: 'red', quantity:0 },
  { src: 'special/new-collection/2-gold.png', category: 'red', quantity: 1 },
  { src: 'special/new-collection/3-gold.png', category: 'red', quantity: 1 },
  { src: 'special/new-collection/5-gold.png', category: 'red', quantity: 1 },
  { src: 'special/new-collection/12-gold.png', category: 'red', quantity: 0 },
  // teddy charms
  { src: 'special/teddy/teddy.png', category: 'teddy', quantity: 3 },
  { src: 'special/teddy/84-gold.png', category: 'teddy', quantity: 11 },
  { src: 'special/teddy/85-gold.png', category: 'teddy', quantity: 9 },
  { src: 'special/teddy/86-gold.png', category: 'teddy', quantity: 3 },
  { src: 'special/teddy/87-gold.png', category: 'teddy', quantity: 3 },
  { src: 'special/teddy/88-gold.png', category: 'teddy', quantity: 6 },
  { src: 'special/teddy/teddy2.png', category: 'teddy', quantity: 3 },
  { src: 'special/teddy/teddy3.png', category: 'teddy', quantity: 6 },
  { src: 'special/teddy/teddy4.png', category: 'teddy', quantity: 9 },
  { src: 'special/teddy/128-gold.png', category: 'teddy', quantity: 9 },
  { src: 'special/teddy/teddy5.png', category: 'teddy', quantity: 9 },
  { src: 'special/teddy/teddy6.png', category: 'teddy', quantity: 11 },
   // girly charms
  { src: 'special/new-collection/11.png', category: 'girly', quantity: 1 },
  { src: 'special/new-collection/33.png', category: 'girly', quantity: 1 },
  { src: 'special/new-collection/29-gold.png', category: 'girly', quantity: 1 },
  { src: 'special/new-collection/30.png', category: 'girly', quantity: 1 },
  { src: 'special/new-collection/31-gold.png', category: 'girly', quantity: 1 },
  { src: 'special/new-collection/33.png', category: 'girly', quantity: 1 },
  { src: 'special/new-collection/36-gold.png', category: 'girly', quantity: 1 },
  { src: 'special/new-collection/37.png', category: 'girly', quantity: 1 },
  { src: 'special/new-collection/38-gold.png', category: 'girly', quantity: 1 },
  { src: 'special/new-collection/39.png', category: 'girly', quantity: 1 },
  { src: 'special/new-collection/47-gold.png', category: 'girly', quantity: 1 },
  { src: 'special/new-collection/48.png', category: 'girly', quantity: 1 },
  { src: 'special/new-collection/50.png', category: 'girly', quantity: 1 },
  { src: 'special/new-collection/51-gold.png', category: 'girly', quantity: 1 },
  { src: 'special/new-collection/53-gold.png', category: 'girly', quantity: 1 },
  { src: 'special/new-collection/54.png', category: 'girly', quantity: 1 },
  { src: 'special/new-collection/55-gold.png', category: 'girly', quantity: 1 },
  { src: 'special/new-collection/58.png', category: 'girly', quantity: 1 },
  { src: 'special/new-collection/59-gold.png', category: 'girly', quantity: 1 },
  { src: 'special/new-collection/7.png', category: 'girly', quantity: 1 },
  { src: 'special/new-collection/15-gold.png', category: 'girly', quantity: 1 },
  // fruity charms
  { src: 'special/new-collection/28.png', category: 'fruity', quantity: 1 },
  { src: 'special/new-collection/32-gold.png', category: 'fruity', quantity: 1 },
  { src: 'special/new-collection/34.png', category: 'fruity', quantity: 0 },
  { src: 'special/new-collection/35-gold.png', category: 'fruity', quantity: 1 },
  { src: 'special/new-collection/40.png', category: 'fruity', quantity: 1 },
  { src: 'special/new-collection/41-gold.png', category: 'fruity', quantity: 1 },
  { src: 'special/new-collection/42.png', category: 'fruity', quantity: 1 },
  { src: 'special/new-collection/43-gold.png', category: 'fruity', quantity: 1 },
  { src: 'special/new-collection/44.png', category: 'fruity', quantity: 1 },
  { src: 'special/new-collection/45-gold.png', category: 'fruity', quantity: 1 },
  { src: 'special/new-collection/46.png', category: 'fruity', quantity: 1 },
  { src: 'special/new-collection/49-gold.png', category: 'fruity', quantity: 1 },
  { src: 'special/new-collection/14-gold.png', category: 'fruity', quantity: 1 },
  { src: 'special/new-collection/10.png', category: 'fruity', quantity: 1 },
  { src: 'special/new-collection/11-gold.png', category: 'fruity', quantity: 1 },
  { src: 'special/new-collection/12.png', category: 'fruity', quantity: 1 },
  { src: 'special/new-collection/13.png', category: 'fruity', quantity: 1 },
  { src: 'special/new-collection/14-gold.png', category: 'fruity', quantity: 1 },
  { src: 'special/new-collection/15.png', category: 'fruity', quantity: 1 },
  { src: 'special/new-collection/16-gold.png', category: 'fruity', quantity: 1 },
  { src: 'special/new-collection/17-gold.png', category: 'fruity', quantity: 1 },
  { src: 'special/new-collection/18.png', category: 'fruity', quantity: 1 },
  { src: 'special/new-collection/19-gold.png', category: 'fruity', quantity: 1 },
  { src: 'special/new-collection/20.png', category: 'fruity', quantity: 1 },
  { src: 'special/new-collection/21.png', category: 'fruity', quantity: 1 },
  { src: 'special/new-collection/22-gold.png', category: 'fruity', quantity: 1 },
  { src: 'special/new-collection/23-gold.png', category: 'fruity', quantity: 1 },
  { src: 'special/new-collection/24.png', category: 'fruity', quantity: 1 },
  { src: 'special/new-collection/25-gold.png', category: 'fruity', quantity: 1 },
  { src: 'special/new-collection/26.png', category: 'fruity', quantity: 1 },
  { src: 'special/new-collection/27-gold.png', category: 'fruity', quantity: 1 },
  { src: 'special/new-collection/28.png', category: 'fruity', quantity: 1 },
  { src: 'special/new-collection/29.png', category: 'fruity', quantity: 1 },
  { src: 'special/new-collection/30-gold.png', category: 'fruity', quantity: 1 },
  { src: 'special/new-collection/31.png', category: 'fruity', quantity: 1 },
  { src: 'special/new-collection/32-gold.png', category: 'fruity', quantity: 1 },
  { src: 'special/new-collection/33-gold.png', category: 'fruity', quantity: 0 },
  { src: 'special/new-collection/34.png', category: 'fruity', quantity: 1 },
  { src: 'special/new-collection/35-gold.png', category: 'fruity', quantity: 1 },
  { src: 'special/new-collection/36.png', category: 'fruity', quantity: 1 },
  { src: 'special/new-collection/37-gold.png', category: 'fruity', quantity: 1 },
  { src: 'special/new-collection/38.png', category: 'fruity', quantity: 1 },
  { src: 'special/new-collection/39-gold.png', category: 'fruity', quantity: 1 },
  { src: 'special/new-collection/40.png', category: 'fruity', quantity: 1 },
  { src: 'special/new-collection/41-gold.png', category: 'fruity', quantity: 1 },
  { src: 'special/new-collection/42.png', category: 'fruity', quantity: 1 },
  { src: 'special/new-collection/43-gold.png', category: 'fruity', quantity: 1 },
  { src: 'special/new-collection/44.png', category: 'fruity', quantity: 1 },
  { src: 'special/new-collection/45-gold.png', category: 'fruity', quantity: 1 },
  { src: 'special/new-collection/46.png', category: 'fruity', quantity: 1 },
  { src: 'special/new-collection/47.png', category: 'fruity', quantity: 1 },
  { src: 'special/new-collection/48-gold.png', category: 'fruity', quantity: 1 },
  { src: 'special/new-collection/49-gold.png', category: 'fruity', quantity: 1 },
  { src: 'special/new-collection/50-gold.png', category: 'fruity', quantity: 1 },
  { src: 'special/new-collection/51.png', category: 'fruity', quantity: 1 },
  { src: 'special/new-collection/85.png', category: 'fruity', quantity: 1 },
  { src: 'special/new-collection/9-gold.png', category: 'fruity', quantity: 1 },
  // fun charms
  { src: 'special/new-collection/52.png', category: 'fun', quantity: 1 },
  { src: 'special/new-collection/56.png', category: 'fun', quantity: 1 },
  { src: 'special/new-collection/57-gold.png', category: 'fun', quantity: 1 },
  { src: 'special/new-collection/52.png', category: 'fun', quantity: 1 },
  { src: 'special/new-collection/53.png', category: 'fun', quantity: 1 },
  { src: 'special/new-collection/54-gold.png', category: 'fun', quantity: 1 },
  { src: 'special/new-collection/55.png', category: 'fun', quantity: 1 },
  { src: 'special/new-collection/56.png', category: 'fun', quantity: 1 },
  { src: 'special/new-collection/57-gold.png', category: 'fun', quantity: 1 },
  { src: 'special/new-collection/58-gold.png', category: 'fun', quantity: 1 },
  { src: 'special/new-collection/59.png', category: 'fun', quantity: 1 },
  { src: 'special/new-collection/60.png', category: 'fun', quantity: 1 },
  { src: 'special/new-collection/61-gold.png', category: 'fun', quantity: 1 },
  { src: 'special/new-collection/82-gold.png', category: 'fun', quantity: 1 },
  { src: 'special/new-collection/83-gold.png', category: 'fun', quantity: 1 },
  { src: 'special/new-collection/11x.png', category: 'fun', quantity: 1 },
  { src: 'special/new-collection/12x.png', category: 'fun', quantity: 1 },
  { src: 'special/new-collection/9x.png', category: 'fun', quantity: 1 },
  // flowers charms
  { src: 'special/new-collection/62.png', category: 'flowers', quantity: 1 },
  { src: 'special/new-collection/63-gold.png', category: 'flowers', quantity: 1 },
  { src: 'special/new-collection/64-gold.png', category: 'flowers', quantity: 1 },
  { src: 'special/new-collection/65.png', category: 'flowers', quantity: 1 },
  { src: 'special/new-collection/66.png', category: 'flowers', quantity: 1 },
  { src: 'special/new-collection/67-gold.png', category: 'flowers', quantity: 1 },
  { src: 'special/new-collection/68-gold.png', category: 'flowers', quantity: 1 },
  { src: 'special/new-collection/69.png', category: 'flowers', quantity: 1 },
  { src: 'special/new-collection/70-gold.png', category: 'flowers', quantity: 1 },
  { src: 'special/new-collection/71.png', category: 'flowers', quantity: 1 },
  { src: 'special/new-collection/72-gold.png', category: 'flowers', quantity: 1 },
  { src: 'special/new-collection/73.png', category: 'flowers', quantity: 1 },
  { src: 'special/new-collection/74-gold.png', category: 'flowers', quantity: 1 },
  { src: 'special/new-collection/75.png', category: 'flowers', quantity: 1 },
  { src: 'special/new-collection/76-gold.png', category: 'flowers', quantity: 1 },
  { src: 'special/new-collection/77.png', category: 'flowers', quantity: 1 },
  { src: 'special/new-collection/78.png', category: 'flowers', quantity: 1 },
  { src: 'special/new-collection/79-gold.png', category: 'flowers', quantity: 1 },
  { src: 'special/new-collection/80.png', category: 'flowers', quantity: 1 },
  { src: 'special/new-collection/81-gold.png', category: 'flowers', quantity: 1 },
  // newc2s charms
  { src: 'special/newc2s/c2103.png', category: 'newc2s', quantity: 0 },
  { src: 'special/newc2s/c2117.png', category: 'newc2s', quantity: 1 },
  { src: 'special/newc2s/c2119.png', category: 'newc2s', quantity: 1 },
  { src: 'special/newc2s/c2129.png', category: 'newc2s', quantity: 1 },
  { src: 'special/newc2s/c2130.png', category: 'newc2s', quantity: 1 },
  { src: 'special/newc2s/c2131.png', category: 'newc2s', quantity: 0 },
  { src: 'special/newc2s/c2134.png', category: 'newc2s', quantity: 1 },
  { src: 'special/newc2s/c2136.png', category: 'newc2s', quantity: 1 },
  { src: 'special/newc2s/c2137.png', category: 'newc2s', quantity: 1 },
  { src: 'special/newc2s/c2138.png', category: 'newc2s', quantity: 1 },
  { src: 'special/newc2s/c2144.png', category: 'newc2s', quantity: 1 },
  { src: 'special/newc2s/c2147.png', category: 'newc2s', quantity: 1 },
  { src: 'special/newc2s/c2150.png', category: 'newc2s', quantity: 4 },
  { src: 'special/newc2s/c2151-gold.png', category: 'newc2s', quantity: 4 },
  { src: 'special/newc2s/c2152.png', category: 'newc2s', quantity: 0 },
  { src: 'special/newc2s/c2153.png', category: 'newc2s', quantity: 1 },
  { src: 'special/newc2s/c2154.png', category: 'newc2s', quantity: 0 },
  { src: 'special/newc2s/c2156.png', category: 'newc2s', quantity: 1 },
  { src: 'special/newc2s/c2159.png', category: 'newc2s', quantity: 1 },
  { src: 'special/newc2s/c2160.png', category: 'newc2s', quantity: 1 },
  { src: 'special/newc2s/c2161.png', category: 'newc2s', quantity: 1 },
  { src: 'special/newc2s/c2162.png', category: 'newc2s', quantity: 1 },
  { src: 'special/newc2s/c2163.png', category: 'newc2s', quantity: 0 },
  { src: 'special/newc2s/c2164.png', category: 'newc2s', quantity: 1 },
  { src: 'special/newc2s/c2166.png', category: 'newc2s', quantity: 1 },
  { src: 'special/newc2s/c226.png', category: 'newc2s', quantity: 7 },
  { src: 'special/newc2s/c227.png', category: 'newc2s', quantity: 7 },
  { src: 'special/newc2s/c231.png', category: 'newc2s', quantity: 7 },
  { src: 'special/newc2s/c232.png', category: 'newc2s', quantity: 7 },
  { src: 'special/newc2s/c233.png', category: 'newc2s', quantity: 7 },
  { src: 'special/newc2s/c236.png', category: 'newc2s', quantity: 7 },
  { src: 'special/newc2s/c239.png', category: 'newc2s', quantity: 7 },
  { src: 'special/newc2s/c240.png', category: 'newc2s', quantity: 7 },
  { src: 'special/newc2s/c241.png', category: 'newc2s', quantity: 7 },
  { src: 'special/newc2s/c243.png', category: 'newc2s', quantity: 7 },
  { src: 'special/newc2s/c256-gold.png', category: 'newc2s', quantity: 7 },
  { src: 'special/newc2s/c257.png', category: 'newc2s', quantity: 5 },
  { src: 'special/newc2s/c258-gold.png', category: 'newc2s', quantity: 6 },
  { src: 'special/newc2s/c259.png', category: 'newc2s', quantity: 6 },
  { src: 'special/newc2s/c260.png', category: 'newc2s', quantity: 1 },
  { src: 'special/newc2s/c262-gold.png', category: 'newc2s', quantity: 5 },
  { src: 'special/newc2s/c263.png', category: 'newc2s', quantity: 5 },
  { src: 'special/newc2s/c264-gold.png', category: 'newc2s', quantity: 5 },
  { src: 'special/newc2s/c265.png', category: 'newc2s', quantity: 5 },
  { src: 'special/newc2s/c266-gold.png', category: 'newc2s', quantity: 5 },
  { src: 'special/newc2s/c267.png', category: 'newc2s', quantity: 5 },
  { src: 'special/newc2s/c268-gold.png', category: 'newc2s', quantity: 5 },
  { src: 'special/newc2s/c269.png', category: 'newc2s', quantity: 5 },
  { src: 'special/newc2s/c270-gold.png', category: 'newc2s', quantity: 5 },
  { src: 'special/newc2s/c271.png', category: 'newc2s', quantity: 4 },
  { src: 'special/newc2s/c272-gold.png', category: 'newc2s', quantity: 5 },
  { src: 'special/newc2s/c273.png', category: 'newc2s', quantity: 4 },
  { src: 'special/newc2s/c274.png', category: 'newc2s', quantity: 4 },
  { src: 'special/newc2s/c275-gold.png', category: 'newc2s', quantity: 3 },
  { src: 'special/newc2s/c276-gold.png', category: 'newc2s', quantity: 3 },
  { src: 'special/newc2s/c277.png', category: 'newc2s', quantity: 3 },
  { src: 'special/newc2s/c278-gold.png', category: 'newc2s', quantity: 4 },
  { src: 'special/newc2s/c279.png', category: 'newc2s', quantity: 3 },
  { src: 'special/newc2s/c280-gold.png', category: 'newc2s', quantity: 4 },
  { src: 'special/newc2s/c281.png', category: 'newc2s', quantity: 4 },
  { src: 'special/newc2s/c282-gold.png', category: 'newc2s', quantity: 5 },
  { src: 'special/newc2s/c283.png', category: 'newc2s', quantity: 4 },
  { src: 'special/newc2s/c284-gold.png', category: 'newc2s', quantity: 0 },
  { src: 'special/newc2s/c285.png', category: 'newc2s', quantity: 0 },
  { src: 'special/newc2s/c286.png', category: 'newc2s', quantity: 5 },
  { src: 'special/newc2s/c287-gold.png', category: 'newc2s', quantity: 4 },
  { src: 'special/newc2s/c288.png', category: 'newc2s', quantity: 4 },
  { src: 'special/newc2s/c289-gold.png', category: 'newc2s', quantity: 4 },
  { src: 'special/newc2s/c290-gold.png', category: 'newc2s', quantity: 3 },
  { src: 'special/newc2s/c291.png', category: 'newc2s', quantity: 4 },
  { src: 'special/newc2s/c292-gold.png', category: 'newc2s', quantity: 3 },
  { src: 'special/newc2s/c293.png', category: 'newc2s', quantity: 4 },
  { src: 'special/newc2s/c294.png', category: 'newc2s', quantity: 3 },
  { src: 'special/newc2s/c295-gold.png', category: 'newc2s', quantity: 4 },
  { src: 'special/newc2s/c298.png', category: 'newc2s', quantity: 1 },
  { src: 'special/newc2s/c299.png', category: 'newc2s', quantity: 1 },
  { src: 'special/newc4s/c430.png', category: 'newc4s', quantity: 1 },
  { src: 'special/newc4s/c431.png', category: 'newc4s', quantity: 1 },
  { src: 'special/newc4s/c432.png', category: 'newc4s', quantity: 1 },
  { src: 'special/newc4s/c433.png', category: 'newc4s', quantity: 1 },
  { src: 'special/newc4s/c434.png', category: 'newc4s', quantity: 1 },
  { src: 'special/newc4s/c435.png', category: 'newc4s', quantity: 1 },
  { src: 'special/newc4s/c436.png', category: 'newc4s', quantity: 1 },
  { src: 'special/newc4s/c437.png', category: 'newc4s', quantity: 1 },
  { src: 'special/newc4s/c438.png', category: 'newc4s', quantity: 1 },
  { src: 'special/newc4s/c439.png', category: 'newc4s', quantity: 1 },
  { src: 'special/newc4s/c440.png', category: 'newc4s', quantity: 1 },
  { src: 'special/newc4s/c441.png', category: 'newc4s', quantity: 1 },
  { src: 'special/newc4s/c442.png', category: 'newc4s', quantity: 1 },
  { src: 'special/newc4s/c443.png', category: 'newc4s', quantity: 1 },
  { src: 'special/newc4s/c444.png', category: 'newc4s', quantity: 1 },
  { src: 'special/newc4s/c445.png', category: 'newc4s', quantity: 1 },
  { src: 'special/newc4s/c446.png', category: 'newc4s', quantity: 1 },
  { src: 'special/newc4s/c447.png', category: 'newc4s', quantity: 1 },

  // butterflies charms
];
 }
    
    if (typeof window.rareCharms === 'undefined') {
         window.rareCharms = [
 
  //
  { src: 'rares/new-collection/10.png', category: 'butterflies', quantity: 1 },
  { src: 'rares/new-collection/11-gold.png', category: 'butterflies', quantity: 1 },
  { src: 'rares/new-collection/12.png', category: 'butterflies', quantity: 6 },
  { src: 'rares/new-collection/14.png', category: 'butterflies', quantity: 6 },
  { src: 'rares/new-collection/16.png', category: 'butterflies', quantity: 5 },
  { src: 'rares/new-collection/17-gold.png', category: 'butterflies', quantity: 6 },
  { src: 'rares/new-collection/18.png', category: 'butterflies', quantity: 4 },
  { src: 'rares/new-collection/19-gold.png', category: 'butterflies', quantity: 6 },
  { src: 'rares/new-collection/20x-gold.png', category: 'butterflies', quantity: 5 },
  { src: 'rares/new-collection/21.png', category: 'butterflies', quantity: 5 },
  { src: 'rares/new-collection/22.png', category: 'butterflies', quantity: 5 },
  { src: 'rares/new-collection/23-gold.png', category: 'butterflies', quantity: 5 },
  { src: 'rares/new-collection/24.png', category: 'butterflies', quantity: 5 },
  { src: 'rares/new-collection/25x-gold.png', category: 'butterflies', quantity: 5 },
  { src: 'rares/new-collection/26.png', category: 'butterflies', quantity: 6 },
  { src: 'rares/new-collection/27w-gold.png', category: 'butterflies', quantity: 10 },
  { src: 'rares/new-collection/8.png', category: 'butterflies', quantity: 5 },
  { src: 'rares/new-collection/9-gold.png', category: 'butterflies', quantity: 5 },
  { src: 'rares/new-collection/13x-gold.png', category: 'butterflies', quantity: 6 },
  // random charms
  { src: 'rares/new-collection/21xx.png', category: 'random', quantity: 1 },
  { src: 'rares/new-collection/2x.png', category: 'random', quantity: 1 },
  { src: 'rares/new-collection/4x.png', category: 'random', quantity: 1 },
  { src: 'rares/new-collection/6x.png', category: 'random', quantity: 1 },
  { src: 'rares/newc2r/c2104.png', category: 'random', quantity: 2 },
  { src: 'rares/newc2r/c2122.png', category: 'random', quantity: 1 },
  { src: 'rares/newc2r/c2125.png', category: 'random', quantity: 1 },
  { src: 'rares/newc2r/c2127.png', category: 'random', quantity: 1 },
  { src: 'rares/newc2r/c2133.png', category: 'random', quantity: 1 },
  { src: 'rares/newc2r/c2148.png', category: 'random', quantity: 1 },
  // disney charms
  { src: 'rares/disney/bluemonster.png', category: 'disney', quantity: 2 },
  { src: 'rares/disney/74-gold.png', category: 'disney', quantity: 3 },
  { src: 'rares/disney/75-gold.png', category: 'disney', quantity: 3 },
  { src: 'rares/disney/76-gold.png', category: 'disney', quantity: 5 },
  { src: 'rares/disney/77-gold.png', category: 'disney', quantity: 3 },
  { src: 'rares/disney/78-gold.png', category: 'disney', quantity: 7 },
  { src: 'rares/disney/79-gold.png', category: 'disney', quantity: 6 },
  { src: 'rares/disney/80-gold.png', category: 'disney', quantity: 7 },
  { src: 'rares/disney/81-gold.png', category: 'disney', quantity: 2 },
  { src: 'rares/disney/82-gold.png', category: 'disney', quantity: 2 },
  { src: 'rares/disney/bunny.png', category: 'disney', quantity: 3 },
  { src: 'rares/disney/disneycat pink.png', category: 'disney', quantity: 6 },
  { src: 'rares/disney/disneycat.png', category: 'disney', quantity: 7 },
  { src: 'rares/disney/fox.png', category: 'disney', quantity: 5 },
  { src: 'rares/disney/greenmonster.png', category: 'disney', quantity: 7 },
  { src: 'rares/disney/pinkstitch.png', category: 'disney', quantity: 3 },
  { src: 'rares/disney/snjab.png', category: 'disney', quantity: 2 },
  { src: 'rares/disney/stitch.png', category: 'disney', quantity: 3 },
  // gold charms
  { src: 'rares/gold/gold.png', category: 'gold', quantity: 0 },
  { src: 'rares/gold/gold17.png', category: 'gold', quantity: 0 },
  { src: 'rares/gold/gold2.png', category: 'gold', quantity: 0 },
  { src: 'rares/gold/gold3.png', category: 'gold', quantity: 0 },
  { src: 'rares/gold/gold4.png', category: 'gold', quantity: 0 },
  { src: 'rares/gold/gold6.png', category: 'gold', quantity: 0 },
  { src: 'rares/gold/gold7.png', category: 'gold', quantity: 0 },
  { src: 'rares/gold/gold8.png', category: 'gold', quantity: 0 },
  { src: 'rares/gold/gold9.png', category: 'gold', quantity: 0 },
  { src: 'rares/gold/gold10.png', category: 'gold', quantity: 0 },
  { src: 'rares/gold/gold11.png', category: 'gold', quantity: 0 },
  { src: 'rares/gold/gold12.png', category: 'gold', quantity: 0 },
  { src: 'rares/gold/gold13.png', category: 'gold', quantity: 0 },
  { src: 'rares/gold/gold14.png', category: 'gold', quantity: 0 },
  { src: 'rares/gold/gold15.png', category: 'gold', quantity: 0 },
  { src: 'rares/new-collection/24-gold.png', category: 'gold', quantity: 0 },
  { src: 'rares/new-collection/25-gold.png', category: 'gold', quantity: 0 },
  { src: 'rares/new-collection/26-gold.png', category: 'gold', quantity: 1 },
  { src: 'rares/new-collection/27-gold.png', category: 'gold', quantity: 1 },
  { src: 'rares/new-collection/28-gold.png', category: 'gold', quantity: 0 },
  { src: 'rares/new-collection/29-gold.png', category: 'gold', quantity: 0 },
  { src: 'rares/newc2r/c225-gold.png', category: 'gold', quantity: 0 },
  // night charms
  { src: 'rares/gold/gold5.png', category: 'night', quantity: 0 },
  { src: 'rares/newc2r/c224.png', category: 'night', quantity: 1 },
  { src: 'rares/newc2r/c229.png', category: 'night', quantity: 7 },
  { src: 'rares/newc2r/c230.png', category: 'night', quantity: 7 },
  { src: 'rares/newc2r/c242.png', category: 'night', quantity: 7 },
  { src: 'rares/newc2r/c25.png', category: 'night', quantity: 1 },
  { src: 'rares/newc2r/c26.png', category: 'night', quantity: 1 },
  { src: 'rares/newc2r/c27.png', category: 'night', quantity: 1 },
  { src: 'rares/newc2r/c28.png', category: 'night', quantity: 1 },
  { src: 'rares/newc2r/c212.png', category: 'night', quantity: 1 },
  // graduation charms
  { src: 'rares/graduation/grad.png', category: 'graduation', quantity: 1 },
  // hgs charms
  { src: 'rares/hgs/hgs.png', category: 'hgs', quantity: 0 },
  { src: 'rares/hgs/hgs2.png', category: 'hgs', quantity: 0 },
  { src: 'rares/hgs/hgs3.png', category: 'hgs', quantity: 0 },
  { src: 'rares/hgs/hgs4.png', category: 'hgs', quantity: 0 },
  { src: 'rares/hgs/25.png', category: 'hgs', quantity: 1 },
  { src: 'rares/hgs/20.png', category: 'hgs', quantity: 1 },
  { src: 'rares/hgs/27.png', category: 'hgs', quantity: 1 },
  { src: 'rares/hgs/21.png', category: 'hgs', quantity: 1 },
  { src: 'rares/hgs/22.png', category: 'hgs', quantity: 0 },
  { src: 'rares/hgs/23.png', category: 'hgs', quantity: 0 },
  { src: 'rares/hgs/24.png', category: 'hgs', quantity: 0 },
  { src: 'rares/hgs/26.png', category: 'hgs', quantity: 1 },
  { src: 'rares/hgs/hgs5.png', category: 'hgs', quantity: 1 },
  { src: 'rares/hgs/hgs6.png', category: 'hgs', quantity: 1 },
  { src: 'rares/hgs/hgs7.png', category: 'hgs', quantity: 0 },
  { src: 'rares/hgs/129.png', category: 'hgs', quantity: 1 },
  { src: 'rares/hgs/130.png', category: 'hgs', quantity: 0 },
  { src: 'rares/hgs/hgs9.png', category: 'hgs', quantity: 1 },
  { src: 'rares/hgs/hgs10.png', category: 'hgs', quantity: 0 },
  { src: 'rares/hgs/hgs11.png', category: 'hgs', quantity: 0 },
  { src: 'rares/hgs/hgs12.png', category: 'hgs', quantity: 0 },
  { src: 'rares/hgs/hgs13.png', category: 'hgs', quantity: 0 },
  { src: 'rares/hgs/hgs14.png', category: 'hgs', quantity: 0 },
  { src: 'rares/hgs/hgs15.png', category: 'hgs', quantity: 0 },
  { src: 'rares/hgs/hgs16.png', category: 'hgs', quantity: 0 },
  { src: 'rares/hgs/hgs17.png', category: 'hgs', quantity: 0 },
  { src: 'rares/new-collection/20-gold.png', category: 'hgs', quantity: 1 },
  { src: 'rares/new-collection/csds.png', category: 'hgs', quantity: 5 },
  { src: 'rares/new-collection/sds.png', category: 'hgs', quantity: 0 },
  { src: 'rares/new-collection/xxx.png', category: 'hgs', quantity: 1 },
  { src: 'rares/new-collection/xxxx.png', category: 'hgs', quantity: 0 },
  { src: 'rares/new-collection/10x.png', category: 'hgs', quantity: 0 },
  { src: 'rares/new-collection/3x.png', category: 'hgs', quantity: 0 },
  { src: 'rares/new-collection/5x.png', category: 'hgs', quantity: 1 },
  { src: 'rares/new-collection/7x.png', category: 'hgs', quantity: 1 },
  { src: 'rares/new-collection/13-gold.png', category: 'hgs', quantity: 0 },
  { src: 'rares/newc2r/c210.png', category: 'hgs', quantity: 1 },
  { src: 'rares/newc2r/c2100.png', category: 'hgs', quantity: 1 },
  { src: 'rares/newc2r/c2101.png', category: 'hgs', quantity: 1 },
  { src: 'rares/newc2r/c2102.png', category: 'hgs', quantity: 1 },
  { src: 'rares/newc2r/c21.png', category: 'hgs', quantity: 1 },
  { src: 'rares/sporty/sporty9.png', category: 'hgs', quantity: 0 },
  { src: 'rares/newc2r/c2105.png', category: 'hgs', quantity: 1 },
  { src: 'rares/newc2r/c2110.png', category: 'hgs', quantity: 1 },
  { src: 'rares/newc2r/c2112.png', category: 'hgs', quantity: 1 },
  { src: 'rares/newc2r/c2113.png', category: 'hgs', quantity: 1 },
  { src: 'rares/newc2r/c2114.png', category: 'hgs', quantity: 1 },
  { src: 'rares/newc2r/c2116.png', category: 'hgs', quantity: 1 },
  { src: 'rares/newc2r/c2118.png', category: 'hgs', quantity: 1 },
  { src: 'rares/newc2r/c2126.png', category: 'hgs', quantity: 1 },
  { src: 'rares/newc2r/c2143.png', category: 'hgs', quantity: 1 },
  { src: 'rares/newc2r/c215.png', category: 'hgs', quantity: 1 },
  { src: 'rares/newc2r/c217.png', category: 'hgs', quantity: 1 },
  { src: 'rares/newc2r/c23.png', category: 'hgs', quantity: 1 },
  { src: 'rares/newc2r/c234.png', category: 'hgs', quantity: 7 },
  { src: 'rares/newc2r/c235.png', category: 'hgs', quantity: 7 },
  { src: 'rares/newc2r/c237.png', category: 'hgs', quantity: 7 },
  { src: 'rares/newc2r/c238.png', category: 'hgs', quantity: 7 },
  { src: 'rares/newc2r/c244.png', category: 'hgs', quantity: 0 },
  { src: 'rares/newc2r/c245.png', category: 'hgs', quantity: 0 },
  { src: 'rares/newc2r/c24-gold.png', category: 'hgs', quantity: 0 },
  { src: 'rares/newc2r/c255-gold.png', category: 'hgs', quantity: 6 },
  { src: 'rares/newc2r/c29-gold.png', category: 'hgs', quantity: 0 },
  { src: 'rares/newc2r/c246.png', category: 'hgs', quantity: 1 },
  { src: 'rares/newc2r/c248.png', category: 'hgs', quantity: 0 },
  { src: 'rares/newc2r/c249.png', category: 'hgs', quantity: 0 },
  { src: 'rares/newc2r/c254.png', category: 'hgs', quantity: 6 },
  { src: 'rares/newc2r/c220.png', category: 'hgs', quantity: 1 },
  { src: 'rares/newc2r/c222.png', category: 'hgs', quantity: 1 },
  { src: 'rares/newc2r/c223.png', category: 'hgs', quantity: 1 },
  { src: 'rares/newc2r/c22.png', category: 'hgs', quantity: 0 },
  // long charms
  { src: 'rares/long/long.png', category: 'long', quantity: 4 },
  { src: 'rares/long/long2.png', category: 'long', quantity: 0},
  { src: 'rares/long/c410.png', category: 'long', quantity: 0 },
  // love charms
  { src: 'rares/love/best.png', category: 'love', quantity: 1 },
  { src: 'rares/love/ends.png', category: 'love', quantity: 1 },
  { src: 'rares/love/fri.png', category: 'love', quantity: 1 },
  { src: 'rares/love/6.png', category: 'love', quantity: 1 },
  { src: 'rares/love/7.png', category: 'love', quantity: 1 },
  { src: 'rares/love/19.png', category: 'love', quantity: 1 },
  { src: 'rares/love/love.png', category: 'love', quantity: 1 },
  { src: 'rares/love/love2.png', category: 'love', quantity: 1 },
  { src: 'rares/love/love3.png', category: 'love', quantity: 0 },
  { src: 'rares/love/love4.png', category: 'love', quantity: 0 },
  { src: 'rares/love/love5.png', category: 'love', quantity: 0 },
  { src: 'rares/love/love6.png', category: 'love', quantity: 0 },
  { src: 'rares/love/love7.png', category: 'love', quantity: 0 },
  { src: 'rares/love/love8.png', category: 'love', quantity: 3 },
  { src: 'rares/love/love9.png', category: 'love', quantity: 1 },
  { src: 'rares/love/love10.png', category: 'love', quantity: 0 },
  { src: 'rares/love/love11.png', category: 'love', quantity:0 },
  { src: 'rares/love/mrmrs1.png', category: 'love', quantity: 1 },
  { src: 'rares/love/mrmrs2.png', category: 'love', quantity: 1 },
  { src: 'rares/love/c218.png', category: 'love', quantity: 1 },
  { src: 'rares/love/c219.png', category: 'love', quantity: 1 },
  { src: 'rares/newc2r/c2120.png', category: 'love', quantity: 1 },
  { src: 'rares/newc2r/c2124.png', category: 'love', quantity: 0},
  { src: 'rares/newc2r/c2146.png', category: 'love', quantity: 1 },
  { src: 'rares/newc2r/c2149.png', category: 'love', quantity: 0 },
  { src: 'rares/newc2r/c228.png', category: 'love', quantity: 7 },
  { src: 'rares/newc2r/c247.png', category: 'love', quantity: 1 },
  { src: 'rares/newc2r/c221.png', category: 'love', quantity: 1 },
  // sanrio charms
  { src: 'rares/sanrio/50-gold.png', category: 'sanrio', quantity: 11 },
  { src: 'rares/sanrio/51.png', category: 'sanrio', quantity: 10 },
  { src: 'rares/sanrio/51-gold.png', category: 'sanrio', quantity: 11 },
  { src: 'rares/sanrio/52.png', category: 'sanrio', quantity: 10 },
  { src: 'rares/sanrio/52-gold.png', category: 'sanrio', quantity: 9 },
  { src: 'rares/sanrio/53.png', category: 'sanrio', quantity: 10 },
  { src: 'rares/sanrio/53-gold.png', category: 'sanrio', quantity: 10 },
  { src: 'rares/sanrio/54.png', category: 'sanrio', quantity: 10 },
  { src: 'rares/sanrio/54-gold.png', category: 'sanrio', quantity: 11 },
  { src: 'rares/sanrio/55.png', category: 'sanrio', quantity: 11 },
  { src: 'rares/sanrio/55-gold.png', category: 'sanrio', quantity: 11 },
  { src: 'rares/sanrio/56.png', category: 'sanrio', quantity: 11 },
  { src: 'rares/sanrio/56-gold.png', category: 'sanrio', quantity: 9 },
  { src: 'rares/sanrio/57.png', category: 'sanrio', quantity: 9 },
  { src: 'rares/sanrio/57-gold.png', category: 'sanrio', quantity: 11 },
  { src: 'rares/sanrio/58.png', category: 'sanrio', quantity: 11 },
  { src: 'rares/sanrio/58-gold.png', category: 'sanrio', quantity: 7 },
  { src: 'rares/sanrio/59.png', category: 'sanrio', quantity: 7 },
  { src: 'rares/sanrio/59-gold.png', category: 'sanrio', quantity: 11 },
  { src: 'rares/sanrio/60.png', category: 'sanrio', quantity: 11 },
  { src: 'rares/sanrio/60-gold.png', category: 'sanrio', quantity: 12 },
  { src: 'rares/sanrio/61.png', category: 'sanrio', quantity: 11 },
  { src: 'rares/sanrio/61-gold.png', category: 'sanrio', quantity: 10 },
  { src: 'rares/sanrio/62.png', category: 'sanrio', quantity: 10 },
  { src: 'rares/sanrio/metalkitty.png', category: 'sanrio', quantity: 9 },
  { src: 'rares/sanrio/83-gold.png', category: 'sanrio', quantity: 9 },
  // sporty charms
  { src: 'rares/sporty/sporty.png', category: 'sporty', quantity: 0 },
  { src: 'rares/sporty/18-gold.png', category: 'sporty', quantity: 0 },
  { src: 'rares/sporty/sporty2.png', category: 'sporty', quantity: 0 },
  { src: 'rares/sporty/sporty3.png', category: 'sporty', quantity: 4 },
  { src: 'rares/sporty/sporty4.png', category: 'sporty', quantity: 0 },
  { src: 'rares/sporty/sporty5.png', category: 'sporty', quantity: 0 },
  { src: 'rares/sporty/sporty6.png', category: 'sporty', quantity: 0 },
  { src: 'rares/sporty/sporty7.png', category: 'sporty', quantity: 2 },
  { src: 'rares/sporty/sporty8.png', category: 'sporty', quantity: 0 },
  { src: 'rares/sporty/30.png', category: 'sporty', quantity: 1 },
  { src: 'rares/sporty/sporty9.png', category: 'sporty', quantity: 0 },
  { src: 'rares/sporty/sporty10.png', category: 'sporty', quantity: 1 },
  { src: 'rares/sporty/sporty11.png', category: 'sporty', quantity: 1 },
  { src: 'rares/sporty/sporty12.png', category: 'sporty', quantity: 0 },
  { src: 'rares/sporty/sporty13.png', category: 'sporty', quantity: 0 },
  { src: 'rares/sporty/sporty14.png', category: 'sporty', quantity: 0 },
  { src: 'rares/sporty/sporty15.png', category: 'sporty', quantity: 1 },
  { src: 'rares/sporty/29.png', category: 'sporty', quantity: 1 },
  { src: 'rares/sporty/31.png', category: 'sporty', quantity: 0 },
  { src: 'rares/new-collection/8x.png', category: 'sporty', quantity: 0 },
  { src: 'rares/newc2r/c2111.png', category: 'sporty', quantity: 1 },
  // dangly charms
  { src: 'rares/dangly/10.png', category: 'dangly', quantity: 0 },
  { src: 'rares/dangly/100-gold.png', category: 'dangly', quantity: 0 },
  { src: 'rares/dangly/101.png', category: 'dangly', quantity: 0 },
  { src: 'rares/dangly/102-gold.png', category: 'dangly', quantity: 0 },
  { src: 'rares/dangly/103.png', category: 'dangly', quantity: 0 },
  { src: 'rares/dangly/104-gold.png', category: 'dangly', quantity: 0 },
  { src: 'rares/dangly/105.png', category: 'dangly', quantity: 0 },
  { src: 'rares/dangly/106-gold.png', category: 'dangly', quantity: 2 },
  { src: 'rares/dangly/107.png', category: 'dangly', quantity: 2 },
  { src: 'rares/dangly/108.png', category: 'dangly', quantity: 2 },
  { src: 'rares/dangly/109-gold.png', category: 'dangly', quantity: 2 },
  { src: 'rares/dangly/11.png', category: 'dangly', quantity: 0 },
  { src: 'rares/dangly/110-gold.png', category: 'dangly', quantity: 1 },
  { src: 'rares/dangly/111.png', category: 'dangly', quantity: 1 },
  { src: 'rares/dangly/112.png', category: 'dangly', quantity: 5 },
  { src: 'rares/dangly/113.png', category: 'dangly', quantity: 0 },
  { src: 'rares/dangly/114.png', category: 'dangly', quantity: 0 },
  { src: 'rares/dangly/115-gold.png', category: 'dangly', quantity: 0 },
  { src: 'rares/dangly/116.png', category: 'dangly', quantity: 0 },
  { src: 'rares/dangly/117-gold.png', category: 'dangly', quantity: 0 },
  { src: 'rares/dangly/118-gold.png', category: 'dangly', quantity: 0 },
  { src: 'rares/dangly/119.png', category: 'dangly', quantity: 0 },
  { src: 'rares/dangly/12-gold.png', category: 'dangly', quantity: 0 },
  { src: 'rares/dangly/120-gold.png', category: 'dangly', quantity: 1 },
  { src: 'rares/dangly/121.png', category: 'dangly', quantity: 1 },
  { src: 'rares/dangly/122-gold.png', category: 'dangly', quantity: 0 },
  { src: 'rares/dangly/123.png', category: 'dangly', quantity: 0 },
  { src: 'rares/dangly/124.png', category: 'dangly', quantity: 0 },
  { src: 'rares/dangly/125-gold.png', category: 'dangly', quantity: 0 },
  { src: 'rares/dangly/126.png', category: 'dangly', quantity: 0 },
  { src: 'rares/dangly/127-gold.png', category: 'dangly', quantity: 0 },
  { src: 'rares/dangly/128.png', category: 'dangly', quantity: 0 },
  { src: 'rares/dangly/129.png', category: 'dangly', quantity: 0 },
  { src: 'rares/dangly/13.png', category: 'dangly', quantity: 0 },
  { src: 'rares/dangly/130-gold.png', category: 'dangly', quantity: 0 },
  { src: 'rares/dangly/131-gold.png', category: 'dangly', quantity: 0 },
  { src: 'rares/dangly/132.png', category: 'dangly', quantity: 0 },
  { src: 'rares/dangly/133-gold.png', category: 'dangly', quantity: 0 },
  { src: 'rares/dangly/134.png', category: 'dangly', quantity: 0 },
  { src: 'rares/dangly/135-gold.png', category: 'dangly', quantity: 0 },
  { src: 'rares/dangly/136.png', category: 'dangly', quantity: 0 },
  { src: 'rares/dangly/137-gold.png', category: 'dangly', quantity: 0 },
  { src: 'rares/dangly/138.png', category: 'dangly', quantity: 0 },
  { src: 'rares/dangly/139-gold.png', category: 'dangly', quantity: 0 },
  { src: 'rares/dangly/14-gold.png', category: 'dangly', quantity: 0 },
  { src: 'rares/dangly/140.png', category: 'dangly', quantity: 0 },
  { src: 'rares/dangly/141-gold.png', category: 'dangly', quantity: 0 },
  { src: 'rares/dangly/142.png', category: 'dangly', quantity: 0 },
  { src: 'rares/dangly/143-gold.png', category: 'dangly', quantity: 0 },
  { src: 'rares/dangly/144.png', category: 'dangly', quantity: 0 },
  { src: 'rares/dangly/145-gold.png', category: 'dangly', quantity: 1 },
  { src: 'rares/dangly/146.png', category: 'dangly', quantity: 1 },
  { src: 'rares/dangly/147-gold.png', category: 'dangly', quantity: 0 },
  { src: 'rares/dangly/148.png', category: 'dangly', quantity: 0 },
  { src: 'rares/dangly/149-gold.png', category: 'dangly', quantity: 0 },
  { src: 'rares/dangly/15-gold.png', category: 'dangly', quantity: 1 },
  { src: 'rares/dangly/150.png', category: 'dangly', quantity: 0 },
  { src: 'rares/dangly/151-gold.png', category: 'dangly', quantity: 0 },
  { src: 'rares/dangly/152.png', category: 'dangly', quantity: 0 },
  { src: 'rares/dangly/153.png', category: 'dangly', quantity: 1 },
  { src: 'rares/dangly/154.png', category: 'dangly', quantity: 0 },
  { src: 'rares/dangly/155-gold.png', category: 'dangly', quantity: 0 },
  { src: 'rares/dangly/156-gold.png', category: 'dangly', quantity: 1 },
  { src: 'rares/dangly/157-gold.png', category: 'dangly', quantity: 0 },
  { src: 'rares/dangly/158.png', category: 'dangly', quantity: 0 },
  { src: 'rares/dangly/159-gold.png', category: 'dangly', quantity: 0 },
  { src: 'rares/dangly/16.png', category: 'dangly', quantity: 1 },
  { src: 'rares/dangly/160.png', category: 'dangly', quantity: 0 },
  { src: 'rares/dangly/161-gold.png', category: 'dangly', quantity: 1 },
  { src: 'rares/dangly/162.png', category: 'dangly', quantity: 1 },
  { src: 'rares/dangly/163-gold.png', category: 'dangly', quantity: 1 },
  { src: 'rares/dangly/164.png', category: 'dangly', quantity: 1 },
  { src: 'rares/dangly/165-gold.png', category: 'dangly', quantity: 0 },
  { src: 'rares/dangly/166.png', category: 'dangly', quantity: 0 },
  { src: 'rares/dangly/167-gold.png', category: 'dangly', quantity: 1 },
  { src: 'rares/dangly/168.png', category: 'dangly', quantity: 1 },
  { src: 'rares/dangly/169-gold.png', category: 'dangly', quantity: 0 },
  { src: 'rares/dangly/170.png', category: 'dangly', quantity: 0 },
  { src: 'rares/dangly/171-gold.png', category: 'dangly', quantity: 0 },
  { src: 'rares/dangly/172.png', category: 'dangly', quantity: 0 },
  { src: 'rares/dangly/173-gold.png', category: 'dangly', quantity: 0 },
  { src: 'rares/dangly/174.png', category: 'dangly', quantity: 0 },
  { src: 'rares/dangly/175-gold.png', category: 'dangly', quantity: 0 },
  { src: 'rares/dangly/176.png', category: 'dangly', quantity: 0 },
  { src: 'rares/dangly/177-gold.png', category: 'dangly', quantity: 0 },
  { src: 'rares/dangly/178.png', category: 'dangly', quantity: 0 },
  { src: 'rares/dangly/179-gold.png', category: 'dangly', quantity: 1 },
  { src: 'rares/dangly/180.png', category: 'dangly', quantity: 1 },
  { src: 'rares/dangly/181-gold.png', category: 'dangly', quantity: 1 },
  { src: 'rares/dangly/182.png', category: 'dangly', quantity: 1 },
  { src: 'rares/dangly/183-gold.png', category: 'dangly', quantity: 0 },
  { src: 'rares/dangly/184.png', category: 'dangly', quantity: 0 },
  { src: 'rares/dangly/185-gold.png', category: 'dangly', quantity: 0 },
  { src: 'rares/dangly/186.png', category: 'dangly', quantity: 0 },
  { src: 'rares/dangly/187.png', category: 'dangly', quantity: 1 },
  { src: 'rares/dangly/188-gold.png', category: 'dangly', quantity: 1 },
  { src: 'rares/dangly/189-gold.png', category: 'dangly', quantity: 1 },
  { src: 'rares/dangly/190.png', category: 'dangly', quantity: 1 },
  { src: 'rares/dangly/191.png', category: 'dangly', quantity: 1 },
  { src: 'rares/dangly/192-gold.png', category: 'dangly', quantity: 0 },
  { src: 'rares/dangly/193.png', category: 'dangly', quantity: 0 },
  { src: 'rares/dangly/194-gold.png', category: 'dangly', quantity: 0 },
  { src: 'rares/dangly/195.png', category: 'dangly', quantity: 0 },
  { src: 'rares/dangly/63-gold.png', category: 'dangly', quantity: 1 },
  { src: 'rares/dangly/64-gold.png', category: 'dangly', quantity: 1 },
  { src: 'rares/dangly/65-gold.png', category: 'dangly', quantity: 1 },
  { src: 'rares/dangly/66-gold.png', category: 'dangly', quantity: 1 },
  { src: 'rares/dangly/67-gold.png', category: 'dangly', quantity: 1 },
  { src: 'rares/dangly/68.png', category: 'dangly', quantity: 1 },
  { src: 'rares/dangly/70.png', category: 'dangly', quantity: 1 },
  { src: 'rares/dangly/71.png', category: 'dangly', quantity: 1 },
  { src: 'rares/dangly/72.png', category: 'dangly', quantity: 1 },
  { src: 'rares/dangly/73.png', category: 'dangly', quantity: 1 },
  { src: 'rares/dangly/74-gold.png', category: 'dangly', quantity: 0 },
  { src: 'rares/dangly/75-gold.png', category: 'dangly', quantity: 1 },
  { src: 'rares/dangly/76-gold.png', category: 'dangly', quantity: 1 },
  { src: 'rares/dangly/77-gold.png', category: 'dangly', quantity: 0 },
  { src: 'rares/dangly/78-gold.png', category: 'dangly', quantity: 1 },
  { src: 'rares/dangly/79.png', category: 'dangly', quantity: 1 },
  { src: 'rares/dangly/80.png', category: 'dangly', quantity: 0 },
  { src: 'rares/dangly/81-gold.png', category: 'dangly', quantity: 0 },
  { src: 'rares/dangly/82.png', category: 'dangly', quantity: 0 },
  { src: 'rares/dangly/83.png', category: 'dangly', quantity: 1 },
  { src: 'rares/dangly/84-gold.png', category: 'dangly', quantity: 0 },
  { src: 'rares/dangly/85.png', category: 'dangly', quantity: 0 },
  { src: 'rares/dangly/86.png', category: 'dangly', quantity: 1 },
  { src: 'rares/dangly/87-gold.png', category: 'dangly', quantity: 1 },
  { src: 'rares/dangly/88-gold.png', category: 'dangly', quantity: 0 },
  { src: 'rares/dangly/89-gold.png', category: 'dangly', quantity: 0 },
  { src: 'rares/dangly/9-gold.png', category: 'dangly', quantity: 0 },
  { src: 'rares/dangly/90.png', category: 'dangly', quantity: 0 },
  { src: 'rares/dangly/91.png', category: 'dangly', quantity: 0 },
  { src: 'rares/dangly/92.png', category: 'dangly', quantity: 0 },
  { src: 'rares/dangly/93.png', category: 'dangly', quantity: 1 },
  { src: 'rares/dangly/94-gold.png', category: 'dangly', quantity: 1 },
  { src: 'rares/dangly/95.png', category: 'dangly', quantity: 1 },
  { src: 'rares/dangly/96-gold.png', category: 'dangly', quantity: 0 },
  { src: 'rares/dangly/97.png', category: 'dangly', quantity: 0 },
  { src: 'rares/dangly/98-gold.png', category: 'dangly', quantity: 2 },
  { src: 'rares/dangly/99.png', category: 'dangly', quantity: 2 },
  { src: 'rares/dangly/dangly.png', category: 'dangly', quantity: 3 },
  { src: 'rares/dangly/16s.png', category: 'dangly', quantity: 1 },
  { src: 'rares/dangly/17.png', category: 'dangly', quantity: 1 },
  { src: 'rares/dangly/18-gold.png', category: 'dangly', quantity: 1 },
  { src: 'rares/dangly/19-gold.png', category: 'dangly', quantity: 1 },
  { src: 'rares/dangly/c2167.png', category: 'dangly', quantity: 1 },
  { src: 'rares/dangly/c2168-gold.png', category: 'dangly', quantity: 1 },
  { src: 'rares/dangly/c2169.png', category: 'dangly', quantity: 0 },
  { src: 'rares/dangly/c2171-gold.png', category: 'dangly', quantity: 0 },
  { src: 'rares/dangly/c2172.png', category: 'dangly', quantity: 0 },
  { src: 'rares/dangly/c2173-gold.png', category: 'dangly', quantity: 0 },
  { src: 'rares/dangly/c2174-gold.png', category: 'dangly', quantity: 1 },
  { src: 'rares/dangly/c2175.png', category: 'dangly', quantity: 1 },
  { src: 'rares/dangly/c2176.png', category: 'dangly', quantity: 0 },
  { src: 'rares/dangly/c2177-gold.png', category: 'dangly', quantity: 0 },
  { src: 'rares/dangly/c2178.png', category: 'dangly', quantity: 1 },
  { src: 'rares/dangly/c2179-gold.png', category: 'dangly', quantity: 1 },
  { src: 'rares/dangly/c2180.png', category: 'dangly', quantity: 2 },
  { src: 'rares/dangly/c2181-gold.png', category: 'dangly', quantity: 2 },
  { src: 'rares/dangly/c2182.png', category: 'dangly', quantity: 1 },
  { src: 'rares/dangly/c2183-gold.png', category: 'dangly', quantity: 1 },
  { src: 'rares/dangly/c2184.png', category: 'dangly', quantity: 0 },
  { src: 'rares/dangly/c2185-gold.png', category: 'dangly', quantity: 0 },
  { src: 'rares/dangly/c2186.png', category: 'dangly', quantity: 1 },
  { src: 'rares/dangly/c2187-gold.png', category: 'dangly', quantity: 1 },
  { src: 'rares/dangly/c2188.png', category: 'dangly', quantity: 2 },
  { src: 'rares/dangly/c2189-gold.png', category: 'dangly', quantity: 2 },
  { src: 'rares/dangly/c2190.png', category: 'dangly', quantity: 2 },
  { src: 'rares/dangly/c2191-gold.png', category: 'dangly', quantity: 2 },
  { src: 'rares/dangly/c2192.png', category: 'dangly', quantity: 1 },
  { src: 'rares/dangly/c2193-gold.png', category: 'dangly', quantity: 1 },
  { src: 'rares/dangly/c2194.png', category: 'dangly', quantity: 0 },
  { src: 'rares/dangly/c2195-gold.png', category: 'dangly', quantity: 0 },
  { src: 'rares/dangly/c2196-gold.png', category: 'dangly', quantity: 1 },
  { src: 'rares/dangly/c2197.png', category: 'dangly', quantity: 1 },
  { src: 'rares/dangly/c2198.png', category: 'dangly', quantity: 0 },
  { src: 'rares/dangly/c2199-gold.png', category: 'dangly', quantity: 0 },
  { src: 'rares/dangly/c2200.png', category: 'dangly', quantity: 2 },
  { src: 'rares/dangly/c2201-gold.png', category: 'dangly', quantity: 2 },
  { src: 'rares/dangly/c2202-gold.png', category: 'dangly', quantity: 1 },
  { src: 'rares/dangly/c2203.png', category: 'dangly', quantity: 1 },
  { src: 'rares/dangly/c2204.png', category: 'dangly', quantity: 1 },
  { src: 'rares/dangly/c2205-gold.png', category: 'dangly', quantity: 1 },
  { src: 'rares/dangly/c2206.png', category: 'dangly', quantity: 0 },
  { src: 'rares/dangly/c2207-gold.png', category: 'dangly', quantity: 0 },
  // pets charms
  { src: 'rares/newc2r/c2145.png', category: 'pets', quantity: 1 },
  { src: 'rares/newc2r/c2135.png', category: 'pets', quantity: 0 },
  { src: 'rares/newc2r/c2115.png', category: 'pets', quantity: 1 },
  { src: 'rares/newc2r/c2107.png', category: 'pets', quantity: 1 },
  { src: 'rares/newc2r/c2108.png', category: 'pets', quantity: 1 },
  { src: 'rares/newc2r/c2106.png', category: 'pets', quantity: 1 },
  { src: 'rares/newc2r/c216.png', category: 'pets', quantity: 1 },
  { src: 'rares/newc2r/c297.png', category: 'pets', quantity: 1 },
  // rcute charms
  { src: 'rares/newc2r/c250.png', category: 'rcute', quantity: 5 },
  { src: 'rares/newc2r/c252.png', category: 'rcute', quantity: 5 },
  { src: 'rares/newc2r/c2128.png', category: 'rcute', quantity: 0 },
  { src: 'rares/newc2r/c211.png', category: 'rcute', quantity: 1 },
  { src: 'rares/newc2r/c2121.png', category: 'rcute', quantity: 1 },
  { src: 'rares/newc2r/c213.png', category: 'rcute', quantity: 1 },
  { src: 'rares/newc2r/c2139.png', category: 'rcute', quantity: 1 },
  { src: 'rares/newc2r/c214.png', category: 'rcute', quantity: 0 },
  { src: 'rares/newc2r/c2142.png', category: 'rcute', quantity: 1 },
  { src: 'rares/newc2r/c2109.png', category: 'rcute', quantity: 1 },
  { src: 'rares/newc2r/c251-gold.png', category: 'rcute', quantity: 5 },
  { src: 'rares/newc2r/c253-gold.png', category: 'rcute', quantity: 5 },
  { src: 'rares/newc2r/c296.png', category: 'rcute', quantity: 1 },
  // funny charms
  { src: 'rares/newc2r/c2132.png', category: 'funny', quantity: 1 },
  { src: 'rares/newc2r/c261.png', category: 'funny', quantity: 1 },
  // careers charms
  { src: 'rares/newc2r/c2140.png', category: 'careers', quantity: 1 },
  { src: 'rares/newc2r/c2141.png', category: 'careers', quantity: 1 },
  // newc3r charms
  { src: 'rares/newc3r/c31.png', category: 'newc3r', quantity: 1 },
  { src: 'rares/newc3r/c310.png', category: 'newc3r', quantity: 1 },
  { src: 'rares/newc3r/c311.png', category: 'newc3r', quantity: 1 },
  { src: 'rares/newc3r/c312.png', category: 'newc3r', quantity: 1 },
  { src: 'rares/newc3r/c313.png', category: 'newc3r', quantity: 1 },
  { src: 'rares/newc3r/c314.png', category: 'newc3r', quantity: 1 },
  { src: 'rares/newc3r/c315.png', category: 'newc3r', quantity: 1 },
  { src: 'rares/newc3r/c316.png', category: 'newc3r', quantity: 1 },
  { src: 'rares/newc3r/c317.png', category: 'newc3r', quantity: 1 },
  { src: 'rares/newc3r/c318.png', category: 'newc3r', quantity: 1 },
  { src: 'rares/newc3r/c32.png', category: 'newc3r', quantity: 1 },
  { src: 'rares/newc3r/c33.png', category: 'newc3r', quantity: 1 },
  { src: 'rares/newc3r/c34.png', category: 'newc3r', quantity: 1 },
  { src: 'rares/newc3r/c35.png', category: 'newc3r', quantity: 1 },
  { src: 'rares/newc3r/c36.png', category: 'newc3r', quantity: 1 },
  { src: 'rares/newc3r/c37.png', category: 'newc3r', quantity: 1 },
  { src: 'rares/newc3r/c38.png', category: 'newc3r', quantity: 1 },
  { src: 'rares/newc3r/c39.png', category: 'newc3r', quantity: 1 },
  // newc4r charms
  { src: 'rares/newc4r/c41.png', category: 'newc4r', quantity: 1 },
  { src: 'rares/newc4r/c42.png', category: 'newc4r', quantity: 1 },
  { src: 'rares/newc4r/c43.png', category: 'newc4r', quantity: 1 },
  { src: 'rares/newc4r/c44.png', category: 'newc4r', quantity: 1 },
  { src: 'rares/newc4r/c45.png', category: 'newc4r', quantity: 1 },
  { src: 'rares/newc4r/c46.png', category: 'newc4r', quantity: 1 },
  { src: 'rares/newc4r/c47.png', category: 'newc4r', quantity: 1 },
  { src: 'rares/newc4r/c48.png', category: 'newc4r', quantity: 1 },
  { src: 'rares/newc4r/c49.png', category: 'newc4r', quantity: 1 },

  { src: 'rares/dangly/c4c4107-gold.png', category: 'dangly', quantity: 1 },
{ src: 'rares/dangly/c4c4108.png', category: 'dangly', quantity: 1 },
{ src: 'rares/dangly/c4c4109.png', category: 'dangly', quantity: 1 },
{ src: 'rares/dangly/c4c4110-gold.png', category: 'dangly', quantity: 1 },
{ src: 'rares/dangly/c4c4111.png', category: 'dangly', quantity: 1 },
{ src: 'rares/dangly/c4c4112-gold.png', category: 'dangly', quantity: 1 },
{ src: 'rares/dangly/c4c4113-gold.png', category: 'dangly', quantity: 1 },
{ src: 'rares/dangly/c4c4114.png', category: 'dangly', quantity: 1 },
{ src: 'rares/dangly/c4c4115-gold.png', category: 'dangly', quantity: 1 },
{ src: 'rares/dangly/c4c4116.png', category: 'dangly', quantity: 1 },
{ src: 'rares/dangly/c4c4117-gold.png', category: 'dangly', quantity: 1 },
{ src: 'rares/dangly/c4c4118.png', category: 'dangly', quantity: 1 },
{ src: 'rares/dangly/c4c4120.png', category: 'dangly', quantity: 1 },
{ src: 'rares/dangly/c4c4121-gold.png', category: 'dangly', quantity: 1 },
{ src: 'rares/dangly/c4c4122.png', category: 'dangly', quantity: 1 },
{ src: 'rares/dangly/c4c4123-gold.png', category: 'dangly', quantity: 1 },
{ src: 'rares/dangly/c4c4124.png', category: 'dangly', quantity: 1 },
{ src: 'rares/dangly/c4c4125-gold.png', category: 'dangly', quantity: 1 },
{ src: 'rares/dangly/c4c4126.png', category: 'dangly', quantity: 1 },
{ src: 'rares/dangly/c4c4127-gold.png', category: 'dangly', quantity: 1 },
{ src: 'rares/dangly/c4c4128.png', category: 'dangly', quantity: 1 },
{ src: 'rares/dangly/c4c4129-gold.png', category: 'dangly', quantity: 1 },
{ src: 'rares/dangly/c4c4130.png', category: 'dangly', quantity: 1 },
{ src: 'rares/dangly/c4c4131-gold.png', category: 'dangly', quantity: 1 },
{ src: 'rares/dangly/c4c4132.png', category: 'dangly', quantity: 1 },
{ src: 'rares/dangly/c4c4133-gold.png', category: 'dangly', quantity: 1 },
{ src: 'rares/dangly/c4c4134.png', category: 'dangly', quantity: 1 },
{ src: 'rares/dangly/c4c4135-gold.png', category: 'dangly', quantity: 1 },
{ src: 'rares/dangly/c4c4136.png', category: 'dangly', quantity: 1 },
{ src: 'rares/dangly/c4c4137-gold.png', category: 'dangly', quantity: 1 },
{ src: 'rares/dangly/c4c4138.png', category: 'dangly', quantity: 1 },
{ src: 'rares/dangly/c4c4139-gold.png', category: 'dangly', quantity: 1 },
{ src: 'rares/dangly/c4c4140.png', category: 'dangly', quantity: 1 },
{ src: 'rares/dangly/c4c5141-gold.png', category: 'dangly', quantity: 1 },
  {src:'rares/newc2r/c2142.png', category: 'winter', quantity: 1},
{src:'rares/newc2r/c28.png', category: 'winter', quantity: 1},
{src:'rares/newc2r/c229.png', category: 'winter', quantity: 1},
{src:'rares/newc2r/c2125.png', category: 'winter', quantity: 1},
{src:'rares/new-collection/2x.png', category: 'winter', quantity: 1},
{src:'special/newc2s/c2155.png', category: 'winter', quantity: 1},
{src:'special/newc2s/c2157.png', category: 'winter', quantity: 1},
{src:'special/newc2s/c2165.png', category: 'winter', quantity: 1},
{src:'special/newc2s/c2158.png', category: 'winter', quantity: 1},
  {src:'rares/winter/30.png', category: 'winter', quantity: 1},
{src:'rares/winter/31.png', category: 'winter', quantity: 1},
{src:'rares/winter/32.png', category: 'winter', quantity: 1},
{src:'rares/winter/33.png', category: 'winter', quantity: 1},
{src:'rares/winter/34.png', category: 'winter', quantity: 1},
{src:'rares/winter/35.png', category: 'winter', quantity: 1},
{src:'rares/winter/36.png', category: 'winter', quantity: 1},
{src:'rares/winter/37.png', category: 'winter', quantity: 1},
{src:'rares/winter/38.png', category: 'winter', quantity: 1},
{src:'rares/winter/39.png', category: 'winter', quantity: 1},
{src:'rares/winter/40.png', category: 'winter', quantity: 1},
{src:'rares/winter/41.png', category: 'winter', quantity: 1},
{src:'rares/winter/42.png', category: 'winter', quantity: 1},
{src:'rares/winter/43.png', category: 'winter', quantity: 1},
{src:'rares/winter/44.png', category: 'winter', quantity: 1},
{src:'rares/winter/45.png', category: 'winter', quantity: 1},
{src:'rares/winter/46.png', category: 'winter', quantity: 1},
{src:'rares/winter/47.png', category: 'winter', quantity: 1},
{src:'rares/winter/48.png', category: 'winter', quantity: 1},
{src:'rares/winter/49.png', category: 'winter', quantity: 1},
{src:'rares/winter/50.png', category: 'winter', quantity: 1},
{src:'rares/winter/51.png', category: 'winter', quantity: 1},
{src:'rares/winter/52.png', category: 'winter', quantity: 1},
{src:'rares/winter/53.png', category: 'winter', quantity: 1},
{src:'rares/winter/54.png', category: 'winter', quantity: 1},
{src:'rares/winter/55.png', category: 'winter', quantity: 1},




];
}
    
    console.log('✅ charms.js loaded successfully');
})();

